// Grounding surface — backend schema for the Grounding lens.
// Mirrors grounding.schema.json / grounding.fixture.json (see
// docs/grounding/). This is the canonical proto, moved here from the
// docs/grounding/ sketch per repo convention (proto/*.proto + generated
// proto/<pkg>/*.pb.go via proto/generate.sh).
//
// IMPORTANT — JSON serialization: the Grounding wire JSON is **snake_case**
// (schema_version, token_span, competing_contract_refs, …) as pinned by
// grounding.fixture.json. protojson's default is camelCase, so the JSON the
// UI consumes is produced by the hand-written, snake_case-tagged Go types
// in internal/grounding (types.go + emit.go), NOT by protojson over these
// messages. These messages are the backend/MCP schema mirror; if a
// protojson path is ever wired up it must set json_name on each field to
// the snake_case form to stay fixture-faithful.
//
// Provenance maps onto the existing RowProvenance tier/source/transform —
// the trusted-coverage count already excludes non-mechanical tiers;
// Grounding is mechanical (tier = "mechanical", model_stamp unset).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grounding.proto

package grounding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroundingState int32

const (
	GroundingState_GROUNDING_STATE_UNSPECIFIED GroundingState = 0
	GroundingState_GROUNDED                    GroundingState = 1 // full signal: linked / qualified / defined. Agent knows.            pass  ●
	GroundingState_GUESSING                    GroundingState = 2 // partial signal: context leans, nothing confirms. Agent infers.     needs-work ◐
	GroundingState_UNGROUNDED                  GroundingState = 3 // no signal: bare collision, nothing binds it. Agent is blind.       fail  ○
	GroundingState_NOT_MENTIONED               GroundingState = 4 // element-rollup only: no concept-doc reference at all (coverage gap, not a finding).
)

// Enum value maps for GroundingState.
var (
	GroundingState_name = map[int32]string{
		0: "GROUNDING_STATE_UNSPECIFIED",
		1: "GROUNDED",
		2: "GUESSING",
		3: "UNGROUNDED",
		4: "NOT_MENTIONED",
	}
	GroundingState_value = map[string]int32{
		"GROUNDING_STATE_UNSPECIFIED": 0,
		"GROUNDED":                    1,
		"GUESSING":                    2,
		"UNGROUNDED":                  3,
		"NOT_MENTIONED":               4,
	}
)

func (x GroundingState) Enum() *GroundingState {
	p := new(GroundingState)
	*p = x
	return p
}

func (x GroundingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroundingState) Descriptor() protoreflect.EnumDescriptor {
	return file_grounding_proto_enumTypes[0].Descriptor()
}

func (GroundingState) Type() protoreflect.EnumType {
	return &file_grounding_proto_enumTypes[0]
}

func (x GroundingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroundingState.Descriptor instead.
func (GroundingState) EnumDescriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{0}
}

type AnchorKind int32

const (
	AnchorKind_ANCHOR_UNSPECIFIED AnchorKind = 0
	AnchorKind_PAGE_TITLE         AnchorKind = 1
	AnchorKind_HEADING            AnchorKind = 2
	AnchorKind_FIRST_USE          AnchorKind = 3
	AnchorKind_DEFINED_TERM       AnchorKind = 4
	AnchorKind_QUALIFIED_MENTION  AnchorKind = 5 // backticked / dotted-qualified name
	AnchorKind_LINK               AnchorKind = 6
)

// Enum value maps for AnchorKind.
var (
	AnchorKind_name = map[int32]string{
		0: "ANCHOR_UNSPECIFIED",
		1: "PAGE_TITLE",
		2: "HEADING",
		3: "FIRST_USE",
		4: "DEFINED_TERM",
		5: "QUALIFIED_MENTION",
		6: "LINK",
	}
	AnchorKind_value = map[string]int32{
		"ANCHOR_UNSPECIFIED": 0,
		"PAGE_TITLE":         1,
		"HEADING":            2,
		"FIRST_USE":          3,
		"DEFINED_TERM":       4,
		"QUALIFIED_MENTION":  5,
		"LINK":               6,
	}
)

func (x AnchorKind) Enum() *AnchorKind {
	p := new(AnchorKind)
	*p = x
	return p
}

func (x AnchorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnchorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_grounding_proto_enumTypes[1].Descriptor()
}

func (AnchorKind) Type() protoreflect.EnumType {
	return &file_grounding_proto_enumTypes[1]
}

func (x AnchorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnchorKind.Descriptor instead.
func (AnchorKind) EnumDescriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{1}
}

type FixKind int32

const (
	FixKind_FIX_UNSPECIFIED FixKind = 0
	FixKind_LINK_FIRST_USE  FixKind = 1
	FixKind_DEFINE_TERM     FixKind = 2
	FixKind_QUALIFY         FixKind = 3
)

// Enum value maps for FixKind.
var (
	FixKind_name = map[int32]string{
		0: "FIX_UNSPECIFIED",
		1: "LINK_FIRST_USE",
		2: "DEFINE_TERM",
		3: "QUALIFY",
	}
	FixKind_value = map[string]int32{
		"FIX_UNSPECIFIED": 0,
		"LINK_FIRST_USE":  1,
		"DEFINE_TERM":     2,
		"QUALIFY":         3,
	}
)

func (x FixKind) Enum() *FixKind {
	p := new(FixKind)
	*p = x
	return p
}

func (x FixKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FixKind) Descriptor() protoreflect.EnumDescriptor {
	return file_grounding_proto_enumTypes[2].Descriptor()
}

func (FixKind) Type() protoreflect.EnumType {
	return &file_grounding_proto_enumTypes[2]
}

func (x FixKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FixKind.Descriptor instead.
func (FixKind) EnumDescriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{2}
}

type GroundingReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // == 1
	Surface        string                 `protobuf:"bytes,2,opt,name=surface,proto3" json:"surface,omitempty"`                                   // "grounding"
	GeneratedAt    string                 `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	ModelStamp     *ModelStamp            `protobuf:"bytes,4,opt,name=model_stamp,json=modelStamp,proto3" json:"model_stamp,omitempty"` // unset => purely mechanical / reproducible
	Repo           string                 `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
	Commit         string                 `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	Library        string                 `protobuf:"bytes,7,opt,name=library,proto3" json:"library,omitempty"`
	LibraryDisplay string                 `protobuf:"bytes,8,opt,name=library_display,json=libraryDisplay,proto3" json:"library_display,omitempty"`
	Summary        *GroundingSummary      `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	DisplayMap     map[string]*StateStyle `protobuf:"bytes,10,rep,name=display_map,json=displayMap,proto3" json:"display_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // keys: grounded|guessing|ungrounded
	Elements       []*GroundingElement    `protobuf:"bytes,11,rep,name=elements,proto3" json:"elements,omitempty"`
	Findings       []*GroundingFinding    `protobuf:"bytes,12,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroundingReport) Reset() {
	*x = GroundingReport{}
	mi := &file_grounding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingReport) ProtoMessage() {}

func (x *GroundingReport) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingReport.ProtoReflect.Descriptor instead.
func (*GroundingReport) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{0}
}

func (x *GroundingReport) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *GroundingReport) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *GroundingReport) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *GroundingReport) GetModelStamp() *ModelStamp {
	if x != nil {
		return x.ModelStamp
	}
	return nil
}

func (x *GroundingReport) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GroundingReport) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GroundingReport) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *GroundingReport) GetLibraryDisplay() string {
	if x != nil {
		return x.LibraryDisplay
	}
	return ""
}

func (x *GroundingReport) GetSummary() *GroundingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GroundingReport) GetDisplayMap() map[string]*StateStyle {
	if x != nil {
		return x.DisplayMap
	}
	return nil
}

func (x *GroundingReport) GetElements() []*GroundingElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *GroundingReport) GetFindings() []*GroundingFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type ModelStamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RunAt         string                 `protobuf:"bytes,3,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelStamp) Reset() {
	*x = ModelStamp{}
	mi := &file_grounding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStamp) ProtoMessage() {}

func (x *ModelStamp) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStamp.ProtoReflect.Descriptor instead.
func (*ModelStamp) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{1}
}

func (x *ModelStamp) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelStamp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelStamp) GetRunAt() string {
	if x != nil {
		return x.RunAt
	}
	return ""
}

type GroundingSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ElementsTotal        int32                  `protobuf:"varint,1,opt,name=elements_total,json=elementsTotal,proto3" json:"elements_total,omitempty"`
	ElementsMentioned    int32                  `protobuf:"varint,2,opt,name=elements_mentioned,json=elementsMentioned,proto3" json:"elements_mentioned,omitempty"`
	ElementsNotMentioned int32                  `protobuf:"varint,3,opt,name=elements_not_mentioned,json=elementsNotMentioned,proto3" json:"elements_not_mentioned,omitempty"`
	ElementsGrounded     int32                  `protobuf:"varint,4,opt,name=elements_grounded,json=elementsGrounded,proto3" json:"elements_grounded,omitempty"`
	ElementsGuessing     int32                  `protobuf:"varint,5,opt,name=elements_guessing,json=elementsGuessing,proto3" json:"elements_guessing,omitempty"`
	ElementsUngrounded   int32                  `protobuf:"varint,6,opt,name=elements_ungrounded,json=elementsUngrounded,proto3" json:"elements_ungrounded,omitempty"`
	ReferencesTotal      int32                  `protobuf:"varint,7,opt,name=references_total,json=referencesTotal,proto3" json:"references_total,omitempty"`
	ReferencesGrounded   int32                  `protobuf:"varint,8,opt,name=references_grounded,json=referencesGrounded,proto3" json:"references_grounded,omitempty"`
	ReferencesGuessing   int32                  `protobuf:"varint,9,opt,name=references_guessing,json=referencesGuessing,proto3" json:"references_guessing,omitempty"`
	ReferencesUngrounded int32                  `protobuf:"varint,10,opt,name=references_ungrounded,json=referencesUngrounded,proto3" json:"references_ungrounded,omitempty"`
	ForcesAGuess         int32                  `protobuf:"varint,11,opt,name=forces_a_guess,json=forcesAGuess,proto3" json:"forces_a_guess,omitempty"` // guessing + ungrounded references — the headline number
	Headline             string                 `protobuf:"bytes,12,opt,name=headline,proto3" json:"headline,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GroundingSummary) Reset() {
	*x = GroundingSummary{}
	mi := &file_grounding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingSummary) ProtoMessage() {}

func (x *GroundingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingSummary.ProtoReflect.Descriptor instead.
func (*GroundingSummary) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{2}
}

func (x *GroundingSummary) GetElementsTotal() int32 {
	if x != nil {
		return x.ElementsTotal
	}
	return 0
}

func (x *GroundingSummary) GetElementsMentioned() int32 {
	if x != nil {
		return x.ElementsMentioned
	}
	return 0
}

func (x *GroundingSummary) GetElementsNotMentioned() int32 {
	if x != nil {
		return x.ElementsNotMentioned
	}
	return 0
}

func (x *GroundingSummary) GetElementsGrounded() int32 {
	if x != nil {
		return x.ElementsGrounded
	}
	return 0
}

func (x *GroundingSummary) GetElementsGuessing() int32 {
	if x != nil {
		return x.ElementsGuessing
	}
	return 0
}

func (x *GroundingSummary) GetElementsUngrounded() int32 {
	if x != nil {
		return x.ElementsUngrounded
	}
	return 0
}

func (x *GroundingSummary) GetReferencesTotal() int32 {
	if x != nil {
		return x.ReferencesTotal
	}
	return 0
}

func (x *GroundingSummary) GetReferencesGrounded() int32 {
	if x != nil {
		return x.ReferencesGrounded
	}
	return 0
}

func (x *GroundingSummary) GetReferencesGuessing() int32 {
	if x != nil {
		return x.ReferencesGuessing
	}
	return 0
}

func (x *GroundingSummary) GetReferencesUngrounded() int32 {
	if x != nil {
		return x.ReferencesUngrounded
	}
	return 0
}

func (x *GroundingSummary) GetForcesAGuess() int32 {
	if x != nil {
		return x.ForcesAGuess
	}
	return 0
}

func (x *GroundingSummary) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

type StateStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`                                   // vivid framing word: Grounded / Guessing / Ungrounded
	WorkingLabel  string                 `protobuf:"bytes,2,opt,name=working_label,json=workingLabel,proto3" json:"working_label,omitempty"` // terse parallel participle: Grounded / Inferred / Ungrounded
	Lighthouse    string                 `protobuf:"bytes,3,opt,name=lighthouse,proto3" json:"lighthouse,omitempty"`                         // pass | needs-work | fail
	Glyph         string                 `protobuf:"bytes,4,opt,name=glyph,proto3" json:"glyph,omitempty"`                                   // ● ◐ ○  (non-color signal)
	Tone          string                 `protobuf:"bytes,5,opt,name=tone,proto3" json:"tone,omitempty"`                                     // green | amber | red
	Blurb         string                 `protobuf:"bytes,6,opt,name=blurb,proto3" json:"blurb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateStyle) Reset() {
	*x = StateStyle{}
	mi := &file_grounding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateStyle) ProtoMessage() {}

func (x *StateStyle) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateStyle.ProtoReflect.Descriptor instead.
func (*StateStyle) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{3}
}

func (x *StateStyle) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StateStyle) GetWorkingLabel() string {
	if x != nil {
		return x.WorkingLabel
	}
	return ""
}

func (x *StateStyle) GetLighthouse() string {
	if x != nil {
		return x.Lighthouse
	}
	return ""
}

func (x *StateStyle) GetGlyph() string {
	if x != nil {
		return x.Glyph
	}
	return ""
}

func (x *StateStyle) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

func (x *StateStyle) GetBlurb() string {
	if x != nil {
		return x.Blurb
	}
	return ""
}

type GroundingElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementId     string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Display       string                 `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                                           // PROTOCOL | METHOD | TYPE ...
	State         GroundingState         `protobuf:"varint,4,opt,name=state,proto3,enum=sheaf.grounding.v1.GroundingState" json:"state,omitempty"` // best state across refs; NOT_MENTIONED if none
	Mentioned     bool                   `protobuf:"varint,5,opt,name=mentioned,proto3" json:"mentioned,omitempty"`
	RefCounts     *RefCounts             `protobuf:"bytes,6,opt,name=ref_counts,json=refCounts,proto3" json:"ref_counts,omitempty"`
	FindingIds    []string               `protobuf:"bytes,7,rep,name=finding_ids,json=findingIds,proto3" json:"finding_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundingElement) Reset() {
	*x = GroundingElement{}
	mi := &file_grounding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingElement) ProtoMessage() {}

func (x *GroundingElement) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingElement.ProtoReflect.Descriptor instead.
func (*GroundingElement) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{4}
}

func (x *GroundingElement) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *GroundingElement) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *GroundingElement) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GroundingElement) GetState() GroundingState {
	if x != nil {
		return x.State
	}
	return GroundingState_GROUNDING_STATE_UNSPECIFIED
}

func (x *GroundingElement) GetMentioned() bool {
	if x != nil {
		return x.Mentioned
	}
	return false
}

func (x *GroundingElement) GetRefCounts() *RefCounts {
	if x != nil {
		return x.RefCounts
	}
	return nil
}

func (x *GroundingElement) GetFindingIds() []string {
	if x != nil {
		return x.FindingIds
	}
	return nil
}

type RefCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grounded      int32                  `protobuf:"varint,1,opt,name=grounded,proto3" json:"grounded,omitempty"`
	Guessing      int32                  `protobuf:"varint,2,opt,name=guessing,proto3" json:"guessing,omitempty"`
	Ungrounded    int32                  `protobuf:"varint,3,opt,name=ungrounded,proto3" json:"ungrounded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefCounts) Reset() {
	*x = RefCounts{}
	mi := &file_grounding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefCounts) ProtoMessage() {}

func (x *RefCounts) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefCounts.ProtoReflect.Descriptor instead.
func (*RefCounts) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{5}
}

func (x *RefCounts) GetGrounded() int32 {
	if x != nil {
		return x.Grounded
	}
	return 0
}

func (x *RefCounts) GetGuessing() int32 {
	if x != nil {
		return x.Guessing
	}
	return 0
}

func (x *RefCounts) GetUngrounded() int32 {
	if x != nil {
		return x.Ungrounded
	}
	return 0
}

type GroundingFinding struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ElementId             string                 `protobuf:"bytes,2,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	ElementDisplay        string                 `protobuf:"bytes,3,opt,name=element_display,json=elementDisplay,proto3" json:"element_display,omitempty"`
	State                 GroundingState         `protobuf:"varint,4,opt,name=state,proto3,enum=sheaf.grounding.v1.GroundingState" json:"state,omitempty"` // grounded | guessing | ungrounded (never not_mentioned)
	SourcePath            string                 `protobuf:"bytes,5,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Line                  int32                  `protobuf:"varint,6,opt,name=line,proto3" json:"line,omitempty"`
	SectionPath           []string               `protobuf:"bytes,7,rep,name=section_path,json=sectionPath,proto3" json:"section_path,omitempty"` // heading stack
	Excerpt               string                 `protobuf:"bytes,8,opt,name=excerpt,proto3" json:"excerpt,omitempty"`                            // the sentence, verbatim
	Token                 string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`                                // the colliding word
	TokenSpan             *Span                  `protobuf:"bytes,10,opt,name=token_span,json=tokenSpan,proto3" json:"token_span,omitempty"`      // highlight offset within excerpt
	Candidates            []*Candidate           `protobuf:"bytes,11,rep,name=candidates,proto3" json:"candidates,omitempty"`
	CompetingContractRefs int32                  `protobuf:"varint,12,opt,name=competing_contract_refs,json=competingContractRefs,proto3" json:"competing_contract_refs,omitempty"` // ranking / blast-radius signal
	Checked               []*CheckedAnchor       `protobuf:"bytes,13,rep,name=checked,proto3" json:"checked,omitempty"`                                                             // the "Sheaf checked ..." audit trail
	Fix                   *Fix                   `protobuf:"bytes,14,opt,name=fix,proto3" json:"fix,omitempty"`                                                                     // unset for grounded findings
	Severity              float64                `protobuf:"fixed64,15,opt,name=severity,proto3" json:"severity,omitempty"`                                                         // 0..1 worklist rank
	Provenance            *Provenance            `protobuf:"bytes,16,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GroundingFinding) Reset() {
	*x = GroundingFinding{}
	mi := &file_grounding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingFinding) ProtoMessage() {}

func (x *GroundingFinding) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingFinding.ProtoReflect.Descriptor instead.
func (*GroundingFinding) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{6}
}

func (x *GroundingFinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroundingFinding) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *GroundingFinding) GetElementDisplay() string {
	if x != nil {
		return x.ElementDisplay
	}
	return ""
}

func (x *GroundingFinding) GetState() GroundingState {
	if x != nil {
		return x.State
	}
	return GroundingState_GROUNDING_STATE_UNSPECIFIED
}

func (x *GroundingFinding) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *GroundingFinding) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *GroundingFinding) GetSectionPath() []string {
	if x != nil {
		return x.SectionPath
	}
	return nil
}

func (x *GroundingFinding) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

func (x *GroundingFinding) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GroundingFinding) GetTokenSpan() *Span {
	if x != nil {
		return x.TokenSpan
	}
	return nil
}

func (x *GroundingFinding) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GroundingFinding) GetCompetingContractRefs() int32 {
	if x != nil {
		return x.CompetingContractRefs
	}
	return 0
}

func (x *GroundingFinding) GetChecked() []*CheckedAnchor {
	if x != nil {
		return x.Checked
	}
	return nil
}

func (x *GroundingFinding) GetFix() *Fix {
	if x != nil {
		return x.Fix
	}
	return nil
}

func (x *GroundingFinding) GetSeverity() float64 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *GroundingFinding) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Len           int32                  `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_grounding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{7}
}

func (x *Span) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Span) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementId     string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"` // empty for non-contract candidates
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // contract | english | other
	IsContract    bool                   `protobuf:"varint,4,opt,name=is_contract,json=isContract,proto3" json:"is_contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_grounding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{8}
}

func (x *Candidate) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *Candidate) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Candidate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Candidate) GetIsContract() bool {
	if x != nil {
		return x.IsContract
	}
	return false
}

type CheckedAnchor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchor        AnchorKind             `protobuf:"varint,1,opt,name=anchor,proto3,enum=sheaf.grounding.v1.AnchorKind" json:"anchor,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckedAnchor) Reset() {
	*x = CheckedAnchor{}
	mi := &file_grounding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckedAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckedAnchor) ProtoMessage() {}

func (x *CheckedAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckedAnchor.ProtoReflect.Descriptor instead.
func (*CheckedAnchor) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{9}
}

func (x *CheckedAnchor) GetAnchor() AnchorKind {
	if x != nil {
		return x.Anchor
	}
	return AnchorKind_ANCHOR_UNSPECIFIED
}

func (x *CheckedAnchor) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CheckedAnchor) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Fix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          FixKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=sheaf.grounding.v1.FixKind" json:"kind,omitempty"`
	Suggestion    string                 `protobuf:"bytes,2,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Markdown      string                 `protobuf:"bytes,3,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fix) Reset() {
	*x = Fix{}
	mi := &file_grounding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fix) ProtoMessage() {}

func (x *Fix) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fix.ProtoReflect.Descriptor instead.
func (*Fix) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{10}
}

func (x *Fix) GetKind() FixKind {
	if x != nil {
		return x.Kind
	}
	return FixKind_FIX_UNSPECIFIED
}

func (x *Fix) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *Fix) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type Provenance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tier           string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"`
	Adapter        string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	AdapterVersion string                 `protobuf:"bytes,3,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_grounding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_grounding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_grounding_proto_rawDescGZIP(), []int{11}
}

func (x *Provenance) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Provenance) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *Provenance) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

var File_grounding_proto protoreflect.FileDescriptor

const file_grounding_proto_rawDesc = "" +
	"\n" +
	"\x0fgrounding.proto\x12\x12sheaf.grounding.v1\"\x9e\x05\n" +
	"\x0fGroundingReport\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x18\n" +
	"\asurface\x18\x02 \x01(\tR\asurface\x12!\n" +
	"\fgenerated_at\x18\x03 \x01(\tR\vgeneratedAt\x12?\n" +
	"\vmodel_stamp\x18\x04 \x01(\v2\x1e.sheaf.grounding.v1.ModelStampR\n" +
	"modelStamp\x12\x12\n" +
	"\x04repo\x18\x05 \x01(\tR\x04repo\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12\x18\n" +
	"\alibrary\x18\a \x01(\tR\alibrary\x12'\n" +
	"\x0flibrary_display\x18\b \x01(\tR\x0elibraryDisplay\x12>\n" +
	"\asummary\x18\t \x01(\v2$.sheaf.grounding.v1.GroundingSummaryR\asummary\x12T\n" +
	"\vdisplay_map\x18\n" +
	" \x03(\v23.sheaf.grounding.v1.GroundingReport.DisplayMapEntryR\n" +
	"displayMap\x12@\n" +
	"\belements\x18\v \x03(\v2$.sheaf.grounding.v1.GroundingElementR\belements\x12@\n" +
	"\bfindings\x18\f \x03(\v2$.sheaf.grounding.v1.GroundingFindingR\bfindings\x1a]\n" +
	"\x0fDisplayMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.sheaf.grounding.v1.StateStyleR\x05value:\x028\x01\"S\n" +
	"\n" +
	"ModelStamp\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x15\n" +
	"\x06run_at\x18\x03 \x01(\tR\x05runAt\"\xad\x04\n" +
	"\x10GroundingSummary\x12%\n" +
	"\x0eelements_total\x18\x01 \x01(\x05R\relementsTotal\x12-\n" +
	"\x12elements_mentioned\x18\x02 \x01(\x05R\x11elementsMentioned\x124\n" +
	"\x16elements_not_mentioned\x18\x03 \x01(\x05R\x14elementsNotMentioned\x12+\n" +
	"\x11elements_grounded\x18\x04 \x01(\x05R\x10elementsGrounded\x12+\n" +
	"\x11elements_guessing\x18\x05 \x01(\x05R\x10elementsGuessing\x12/\n" +
	"\x13elements_ungrounded\x18\x06 \x01(\x05R\x12elementsUngrounded\x12)\n" +
	"\x10references_total\x18\a \x01(\x05R\x0freferencesTotal\x12/\n" +
	"\x13references_grounded\x18\b \x01(\x05R\x12referencesGrounded\x12/\n" +
	"\x13references_guessing\x18\t \x01(\x05R\x12referencesGuessing\x123\n" +
	"\x15references_ungrounded\x18\n" +
	" \x01(\x05R\x14referencesUngrounded\x12$\n" +
	"\x0eforces_a_guess\x18\v \x01(\x05R\fforcesAGuess\x12\x1a\n" +
	"\bheadline\x18\f \x01(\tR\bheadline\"\xa7\x01\n" +
	"\n" +
	"StateStyle\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12#\n" +
	"\rworking_label\x18\x02 \x01(\tR\fworkingLabel\x12\x1e\n" +
	"\n" +
	"lighthouse\x18\x03 \x01(\tR\n" +
	"lighthouse\x12\x14\n" +
	"\x05glyph\x18\x04 \x01(\tR\x05glyph\x12\x12\n" +
	"\x04tone\x18\x05 \x01(\tR\x04tone\x12\x14\n" +
	"\x05blurb\x18\x06 \x01(\tR\x05blurb\"\x96\x02\n" +
	"\x10GroundingElement\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x128\n" +
	"\x05state\x18\x04 \x01(\x0e2\".sheaf.grounding.v1.GroundingStateR\x05state\x12\x1c\n" +
	"\tmentioned\x18\x05 \x01(\bR\tmentioned\x12<\n" +
	"\n" +
	"ref_counts\x18\x06 \x01(\v2\x1d.sheaf.grounding.v1.RefCountsR\trefCounts\x12\x1f\n" +
	"\vfinding_ids\x18\a \x03(\tR\n" +
	"findingIds\"c\n" +
	"\tRefCounts\x12\x1a\n" +
	"\bgrounded\x18\x01 \x01(\x05R\bgrounded\x12\x1a\n" +
	"\bguessing\x18\x02 \x01(\x05R\bguessing\x12\x1e\n" +
	"\n" +
	"ungrounded\x18\x03 \x01(\x05R\n" +
	"ungrounded\"\xa0\x05\n" +
	"\x10GroundingFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"element_id\x18\x02 \x01(\tR\telementId\x12'\n" +
	"\x0felement_display\x18\x03 \x01(\tR\x0eelementDisplay\x128\n" +
	"\x05state\x18\x04 \x01(\x0e2\".sheaf.grounding.v1.GroundingStateR\x05state\x12\x1f\n" +
	"\vsource_path\x18\x05 \x01(\tR\n" +
	"sourcePath\x12\x12\n" +
	"\x04line\x18\x06 \x01(\x05R\x04line\x12!\n" +
	"\fsection_path\x18\a \x03(\tR\vsectionPath\x12\x18\n" +
	"\aexcerpt\x18\b \x01(\tR\aexcerpt\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\x127\n" +
	"\n" +
	"token_span\x18\n" +
	" \x01(\v2\x18.sheaf.grounding.v1.SpanR\ttokenSpan\x12=\n" +
	"\n" +
	"candidates\x18\v \x03(\v2\x1d.sheaf.grounding.v1.CandidateR\n" +
	"candidates\x126\n" +
	"\x17competing_contract_refs\x18\f \x01(\x05R\x15competingContractRefs\x12;\n" +
	"\achecked\x18\r \x03(\v2!.sheaf.grounding.v1.CheckedAnchorR\achecked\x12)\n" +
	"\x03fix\x18\x0e \x01(\v2\x17.sheaf.grounding.v1.FixR\x03fix\x12\x1a\n" +
	"\bseverity\x18\x0f \x01(\x01R\bseverity\x12>\n" +
	"\n" +
	"provenance\x18\x10 \x01(\v2\x1e.sheaf.grounding.v1.ProvenanceR\n" +
	"provenance\".\n" +
	"\x04Span\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03len\x18\x02 \x01(\x05R\x03len\"u\n" +
	"\tCandidate\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1f\n" +
	"\vis_contract\x18\x04 \x01(\bR\n" +
	"isContract\"u\n" +
	"\rCheckedAnchor\x126\n" +
	"\x06anchor\x18\x01 \x01(\x0e2\x1e.sheaf.grounding.v1.AnchorKindR\x06anchor\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"r\n" +
	"\x03Fix\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.sheaf.grounding.v1.FixKindR\x04kind\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x02 \x01(\tR\n" +
	"suggestion\x12\x1a\n" +
	"\bmarkdown\x18\x03 \x01(\tR\bmarkdown\"c\n" +
	"\n" +
	"Provenance\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12'\n" +
	"\x0fadapter_version\x18\x03 \x01(\tR\x0eadapterVersion*p\n" +
	"\x0eGroundingState\x12\x1f\n" +
	"\x1bGROUNDING_STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bGROUNDED\x10\x01\x12\f\n" +
	"\bGUESSING\x10\x02\x12\x0e\n" +
	"\n" +
	"UNGROUNDED\x10\x03\x12\x11\n" +
	"\rNOT_MENTIONED\x10\x04*\x83\x01\n" +
	"\n" +
	"AnchorKind\x12\x16\n" +
	"\x12ANCHOR_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"PAGE_TITLE\x10\x01\x12\v\n" +
	"\aHEADING\x10\x02\x12\r\n" +
	"\tFIRST_USE\x10\x03\x12\x10\n" +
	"\fDEFINED_TERM\x10\x04\x12\x15\n" +
	"\x11QUALIFIED_MENTION\x10\x05\x12\b\n" +
	"\x04LINK\x10\x06*P\n" +
	"\aFixKind\x12\x13\n" +
	"\x0fFIX_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLINK_FIRST_USE\x10\x01\x12\x0f\n" +
	"\vDEFINE_TERM\x10\x02\x12\v\n" +
	"\aQUALIFY\x10\x03B-Z+github.com/sheaf-data/sheaf/proto/groundingb\x06proto3"

var (
	file_grounding_proto_rawDescOnce sync.Once
	file_grounding_proto_rawDescData []byte
)

func file_grounding_proto_rawDescGZIP() []byte {
	file_grounding_proto_rawDescOnce.Do(func() {
		file_grounding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grounding_proto_rawDesc), len(file_grounding_proto_rawDesc)))
	})
	return file_grounding_proto_rawDescData
}

var file_grounding_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grounding_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_grounding_proto_goTypes = []any{
	(GroundingState)(0),      // 0: sheaf.grounding.v1.GroundingState
	(AnchorKind)(0),          // 1: sheaf.grounding.v1.AnchorKind
	(FixKind)(0),             // 2: sheaf.grounding.v1.FixKind
	(*GroundingReport)(nil),  // 3: sheaf.grounding.v1.GroundingReport
	(*ModelStamp)(nil),       // 4: sheaf.grounding.v1.ModelStamp
	(*GroundingSummary)(nil), // 5: sheaf.grounding.v1.GroundingSummary
	(*StateStyle)(nil),       // 6: sheaf.grounding.v1.StateStyle
	(*GroundingElement)(nil), // 7: sheaf.grounding.v1.GroundingElement
	(*RefCounts)(nil),        // 8: sheaf.grounding.v1.RefCounts
	(*GroundingFinding)(nil), // 9: sheaf.grounding.v1.GroundingFinding
	(*Span)(nil),             // 10: sheaf.grounding.v1.Span
	(*Candidate)(nil),        // 11: sheaf.grounding.v1.Candidate
	(*CheckedAnchor)(nil),    // 12: sheaf.grounding.v1.CheckedAnchor
	(*Fix)(nil),              // 13: sheaf.grounding.v1.Fix
	(*Provenance)(nil),       // 14: sheaf.grounding.v1.Provenance
	nil,                      // 15: sheaf.grounding.v1.GroundingReport.DisplayMapEntry
}
var file_grounding_proto_depIdxs = []int32{
	4,  // 0: sheaf.grounding.v1.GroundingReport.model_stamp:type_name -> sheaf.grounding.v1.ModelStamp
	5,  // 1: sheaf.grounding.v1.GroundingReport.summary:type_name -> sheaf.grounding.v1.GroundingSummary
	15, // 2: sheaf.grounding.v1.GroundingReport.display_map:type_name -> sheaf.grounding.v1.GroundingReport.DisplayMapEntry
	7,  // 3: sheaf.grounding.v1.GroundingReport.elements:type_name -> sheaf.grounding.v1.GroundingElement
	9,  // 4: sheaf.grounding.v1.GroundingReport.findings:type_name -> sheaf.grounding.v1.GroundingFinding
	0,  // 5: sheaf.grounding.v1.GroundingElement.state:type_name -> sheaf.grounding.v1.GroundingState
	8,  // 6: sheaf.grounding.v1.GroundingElement.ref_counts:type_name -> sheaf.grounding.v1.RefCounts
	0,  // 7: sheaf.grounding.v1.GroundingFinding.state:type_name -> sheaf.grounding.v1.GroundingState
	10, // 8: sheaf.grounding.v1.GroundingFinding.token_span:type_name -> sheaf.grounding.v1.Span
	11, // 9: sheaf.grounding.v1.GroundingFinding.candidates:type_name -> sheaf.grounding.v1.Candidate
	12, // 10: sheaf.grounding.v1.GroundingFinding.checked:type_name -> sheaf.grounding.v1.CheckedAnchor
	13, // 11: sheaf.grounding.v1.GroundingFinding.fix:type_name -> sheaf.grounding.v1.Fix
	14, // 12: sheaf.grounding.v1.GroundingFinding.provenance:type_name -> sheaf.grounding.v1.Provenance
	1,  // 13: sheaf.grounding.v1.CheckedAnchor.anchor:type_name -> sheaf.grounding.v1.AnchorKind
	2,  // 14: sheaf.grounding.v1.Fix.kind:type_name -> sheaf.grounding.v1.FixKind
	6,  // 15: sheaf.grounding.v1.GroundingReport.DisplayMapEntry.value:type_name -> sheaf.grounding.v1.StateStyle
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_grounding_proto_init() }
func file_grounding_proto_init() {
	if File_grounding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grounding_proto_rawDesc), len(file_grounding_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grounding_proto_goTypes,
		DependencyIndexes: file_grounding_proto_depIdxs,
		EnumInfos:         file_grounding_proto_enumTypes,
		MessageInfos:      file_grounding_proto_msgTypes,
	}.Build()
	File_grounding_proto = out.File
	file_grounding_proto_goTypes = nil
	file_grounding_proto_depIdxs = nil
}
