// TestCase — a unit of validated behavior emitted by test parsers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test_case.proto

package testcase

import (
	common "github.com/sheaf-data/sheaf/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssertionRef is a reference to a specific assertion within a test.
// Currently used by the gtest adapter to surface EXPECT/ASSERT lines.
type AssertionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          uint32                 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Macro         string                 `protobuf:"bytes,2,opt,name=macro,proto3" json:"macro,omitempty"`     // "EXPECT_EQ", "ASSERT_TRUE", etc.
	Excerpt       string                 `protobuf:"bytes,3,opt,name=excerpt,proto3" json:"excerpt,omitempty"` // short excerpt of the assertion expression
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertionRef) Reset() {
	*x = AssertionRef{}
	mi := &file_test_case_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertionRef) ProtoMessage() {}

func (x *AssertionRef) ProtoReflect() protoreflect.Message {
	mi := &file_test_case_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertionRef.ProtoReflect.Descriptor instead.
func (*AssertionRef) Descriptor() ([]byte, []int) {
	return file_test_case_proto_rawDescGZIP(), []int{0}
}

func (x *AssertionRef) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *AssertionRef) GetMacro() string {
	if x != nil {
		return x.Macro
	}
	return ""
}

func (x *AssertionRef) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

type TestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // canonical ID, e.g. "FooTest.BarReturnsTrue"
	Framework     string                 `protobuf:"bytes,2,opt,name=framework,proto3" json:"framework,omitempty"` // "gtest" | "rust-test" | "bats" | ...
	Location      *common.SourceLocation `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	SourceHash    string                 `protobuf:"bytes,4,opt,name=source_hash,json=sourceHash,proto3" json:"source_hash,omitempty"` // content hash of test body
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                               // raw name from source
	NameTokens    []string               `protobuf:"bytes,6,rep,name=name_tokens,json=nameTokens,proto3" json:"name_tokens,omitempty"` // normalized tokens for matching
	Imports       []string               `protobuf:"bytes,7,rep,name=imports,proto3" json:"imports,omitempty"`                         // imported modules / namespaces / packages
	Assertions    []*AssertionRef        `protobuf:"bytes,8,rep,name=assertions,proto3" json:"assertions,omitempty"`
	ContractRefs  []string               `protobuf:"bytes,9,rep,name=contract_refs,json=contractRefs,proto3" json:"contract_refs,omitempty"` // ContractElement IDs (populated by indexer)
	EcosystemMeta *structpb.Struct       `protobuf:"bytes,10,opt,name=ecosystem_meta,json=ecosystemMeta,proto3" json:"ecosystem_meta,omitempty"`
	// provenance records which tier produced this test case. Deterministic
	// for all slice-1 test parsers; the field exists so LLM-adjudicated
	// attribution edges (slice 2) can carry tier without a schema change.
	Provenance    *common.RowProvenance `protobuf:"bytes,11,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_test_case_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_test_case_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_test_case_proto_rawDescGZIP(), []int{1}
}

func (x *TestCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCase) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *TestCase) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TestCase) GetSourceHash() string {
	if x != nil {
		return x.SourceHash
	}
	return ""
}

func (x *TestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestCase) GetNameTokens() []string {
	if x != nil {
		return x.NameTokens
	}
	return nil
}

func (x *TestCase) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *TestCase) GetAssertions() []*AssertionRef {
	if x != nil {
		return x.Assertions
	}
	return nil
}

func (x *TestCase) GetContractRefs() []string {
	if x != nil {
		return x.ContractRefs
	}
	return nil
}

func (x *TestCase) GetEcosystemMeta() *structpb.Struct {
	if x != nil {
		return x.EcosystemMeta
	}
	return nil
}

func (x *TestCase) GetProvenance() *common.RowProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

var File_test_case_proto protoreflect.FileDescriptor

const file_test_case_proto_rawDesc = "" +
	"\n" +
	"\x0ftest_case.proto\x12\x11sheaf.testcase.v1\x1a\fcommon.proto\x1a\x1cgoogle/protobuf/struct.proto\"R\n" +
	"\fAssertionRef\x12\x12\n" +
	"\x04line\x18\x01 \x01(\rR\x04line\x12\x14\n" +
	"\x05macro\x18\x02 \x01(\tR\x05macro\x12\x18\n" +
	"\aexcerpt\x18\x03 \x01(\tR\aexcerpt\"\xcb\x03\n" +
	"\bTestCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tframework\x18\x02 \x01(\tR\tframework\x12;\n" +
	"\blocation\x18\x03 \x01(\v2\x1f.sheaf.common.v1.SourceLocationR\blocation\x12\x1f\n" +
	"\vsource_hash\x18\x04 \x01(\tR\n" +
	"sourceHash\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1f\n" +
	"\vname_tokens\x18\x06 \x03(\tR\n" +
	"nameTokens\x12\x18\n" +
	"\aimports\x18\a \x03(\tR\aimports\x12?\n" +
	"\n" +
	"assertions\x18\b \x03(\v2\x1f.sheaf.testcase.v1.AssertionRefR\n" +
	"assertions\x12#\n" +
	"\rcontract_refs\x18\t \x03(\tR\fcontractRefs\x12>\n" +
	"\x0eecosystem_meta\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\recosystemMeta\x12>\n" +
	"\n" +
	"provenance\x18\v \x01(\v2\x1e.sheaf.common.v1.RowProvenanceR\n" +
	"provenanceB,Z*github.com/sheaf-data/sheaf/proto/testcaseb\x06proto3"

var (
	file_test_case_proto_rawDescOnce sync.Once
	file_test_case_proto_rawDescData []byte
)

func file_test_case_proto_rawDescGZIP() []byte {
	file_test_case_proto_rawDescOnce.Do(func() {
		file_test_case_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_case_proto_rawDesc), len(file_test_case_proto_rawDesc)))
	})
	return file_test_case_proto_rawDescData
}

var file_test_case_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_case_proto_goTypes = []any{
	(*AssertionRef)(nil),          // 0: sheaf.testcase.v1.AssertionRef
	(*TestCase)(nil),              // 1: sheaf.testcase.v1.TestCase
	(*common.SourceLocation)(nil), // 2: sheaf.common.v1.SourceLocation
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*common.RowProvenance)(nil),  // 4: sheaf.common.v1.RowProvenance
}
var file_test_case_proto_depIdxs = []int32{
	2, // 0: sheaf.testcase.v1.TestCase.location:type_name -> sheaf.common.v1.SourceLocation
	0, // 1: sheaf.testcase.v1.TestCase.assertions:type_name -> sheaf.testcase.v1.AssertionRef
	3, // 2: sheaf.testcase.v1.TestCase.ecosystem_meta:type_name -> google.protobuf.Struct
	4, // 3: sheaf.testcase.v1.TestCase.provenance:type_name -> sheaf.common.v1.RowProvenance
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_test_case_proto_init() }
func file_test_case_proto_init() {
	if File_test_case_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_case_proto_rawDesc), len(file_test_case_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_case_proto_goTypes,
		DependencyIndexes: file_test_case_proto_depIdxs,
		MessageInfos:      file_test_case_proto_msgTypes,
	}.Build()
	File_test_case_proto = out.File
	file_test_case_proto_goTypes = nil
	file_test_case_proto_depIdxs = nil
}
