# Source map used to produce docs/examples/fuchsia-io-coverage/

version: 1

category { dotted_path: "docs.reference" }

category {
  dotted_path: "tests.unit_tests"
  paths: "src/storage/lib/vfs/cpp/tests/**"
  paths: "src/storage/lib/vfs/cpp/**/*_test.cc"
  paths: "src/storage/lib/vfs/cpp/**/*_tests.cc"
}
