// DocClaim — a reference from a doc source to a contract element.
//
// Both human-written prose (markdown) and rendered references
// (fidldoc, clidoc) produce DocClaims; substance grading distinguishes
// them downstream.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: doc_claim.proto

package docclaim

import (
	common "github.com/sheaf-data/sheaf/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocClaim kinds let the indexer route claims into the right buckets.
type DocClaimKind int32

const (
	DocClaimKind_DOC_CLAIM_KIND_UNSPECIFIED DocClaimKind = 0
	DocClaimKind_REFERENCE                  DocClaimKind = 1 // from a rendered-reference bundle (fidldoc/clidoc)
	DocClaimKind_PROSE_MENTION              DocClaimKind = 2 // from human-authored prose (markdown)
	DocClaimKind_EXAMPLE                    DocClaimKind = 3 // from a code block inside prose
	// WORKFLOW — a multi-element sequence claim. Emitted by the
	// workflows adapter when a single doc page (recipe, tutorial,
	// task) names two-or-more contract elements in sequence. The
	// ContractRefs list is ordered: refs[0] is the first command in
	// the sequence, refs[N-1] is the last. Single-element claims do
	// not use this kind — they are EXAMPLE or REFERENCE.
	DocClaimKind_WORKFLOW DocClaimKind = 4
)

// Enum value maps for DocClaimKind.
var (
	DocClaimKind_name = map[int32]string{
		0: "DOC_CLAIM_KIND_UNSPECIFIED",
		1: "REFERENCE",
		2: "PROSE_MENTION",
		3: "EXAMPLE",
		4: "WORKFLOW",
	}
	DocClaimKind_value = map[string]int32{
		"DOC_CLAIM_KIND_UNSPECIFIED": 0,
		"REFERENCE":                  1,
		"PROSE_MENTION":              2,
		"EXAMPLE":                    3,
		"WORKFLOW":                   4,
	}
)

func (x DocClaimKind) Enum() *DocClaimKind {
	p := new(DocClaimKind)
	*p = x
	return p
}

func (x DocClaimKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocClaimKind) Descriptor() protoreflect.EnumDescriptor {
	return file_doc_claim_proto_enumTypes[0].Descriptor()
}

func (DocClaimKind) Type() protoreflect.EnumType {
	return &file_doc_claim_proto_enumTypes[0]
}

func (x DocClaimKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocClaimKind.Descriptor instead.
func (DocClaimKind) EnumDescriptor() ([]byte, []int) {
	return file_doc_claim_proto_rawDescGZIP(), []int{0}
}

type DocClaim struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SourcePath   string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Location     *common.SourceLocation `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	RawText      string                 `protobuf:"bytes,3,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`                // short excerpt, typically <=300 chars
	ContractRefs []string               `protobuf:"bytes,4,rep,name=contract_refs,json=contractRefs,proto3" json:"contract_refs,omitempty"` // ContractElement IDs (populated by indexer)
	Url          string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                       // canonical published URL if known
	Substance    common.Substance       `protobuf:"varint,6,opt,name=substance,proto3,enum=sheaf.common.v1.Substance" json:"substance,omitempty"`
	WordCount    uint32                 `protobuf:"varint,7,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	Kind         DocClaimKind           `protobuf:"varint,8,opt,name=kind,proto3,enum=sheaf.docclaim.v1.DocClaimKind" json:"kind,omitempty"`
	Adapter      string                 `protobuf:"bytes,9,opt,name=adapter,proto3" json:"adapter,omitempty"` // adapter that produced this claim
	// section_path is the heading stack at the point of emission,
	// outermost first. For a flag mentioned under `## Command-line
	// options` → `### Filtering`, section_path = ["Command-line
	// options", "Filtering"]. Empty when the mention sits outside
	// any heading (preamble), or when the source format has no
	// heading structure.
	//
	// v1 tracks H1/H2/H3 only; deeper nesting rolls up to the
	// nearest tracked level. Adapters whose source has no
	// heading-equivalent structure leave this empty.
	SectionPath []string `protobuf:"bytes,10,rep,name=section_path,json=sectionPath,proto3" json:"section_path,omitempty"`
	// provenance records which tier produced this claim. Deterministic
	// for all slice-1 doc parsers; the field exists so LLM-adjudicated
	// attribution edges (slice 2) can carry tier without a schema change.
	Provenance    *common.RowProvenance `protobuf:"bytes,11,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocClaim) Reset() {
	*x = DocClaim{}
	mi := &file_doc_claim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocClaim) ProtoMessage() {}

func (x *DocClaim) ProtoReflect() protoreflect.Message {
	mi := &file_doc_claim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocClaim.ProtoReflect.Descriptor instead.
func (*DocClaim) Descriptor() ([]byte, []int) {
	return file_doc_claim_proto_rawDescGZIP(), []int{0}
}

func (x *DocClaim) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *DocClaim) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *DocClaim) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *DocClaim) GetContractRefs() []string {
	if x != nil {
		return x.ContractRefs
	}
	return nil
}

func (x *DocClaim) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DocClaim) GetSubstance() common.Substance {
	if x != nil {
		return x.Substance
	}
	return common.Substance(0)
}

func (x *DocClaim) GetWordCount() uint32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *DocClaim) GetKind() DocClaimKind {
	if x != nil {
		return x.Kind
	}
	return DocClaimKind_DOC_CLAIM_KIND_UNSPECIFIED
}

func (x *DocClaim) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *DocClaim) GetSectionPath() []string {
	if x != nil {
		return x.SectionPath
	}
	return nil
}

func (x *DocClaim) GetProvenance() *common.RowProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

var File_doc_claim_proto protoreflect.FileDescriptor

const file_doc_claim_proto_rawDesc = "" +
	"\n" +
	"\x0fdoc_claim.proto\x12\x11sheaf.docclaim.v1\x1a\fcommon.proto\"\xc5\x03\n" +
	"\bDocClaim\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12;\n" +
	"\blocation\x18\x02 \x01(\v2\x1f.sheaf.common.v1.SourceLocationR\blocation\x12\x19\n" +
	"\braw_text\x18\x03 \x01(\tR\arawText\x12#\n" +
	"\rcontract_refs\x18\x04 \x03(\tR\fcontractRefs\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x128\n" +
	"\tsubstance\x18\x06 \x01(\x0e2\x1a.sheaf.common.v1.SubstanceR\tsubstance\x12\x1d\n" +
	"\n" +
	"word_count\x18\a \x01(\rR\twordCount\x123\n" +
	"\x04kind\x18\b \x01(\x0e2\x1f.sheaf.docclaim.v1.DocClaimKindR\x04kind\x12\x18\n" +
	"\aadapter\x18\t \x01(\tR\aadapter\x12!\n" +
	"\fsection_path\x18\n" +
	" \x03(\tR\vsectionPath\x12>\n" +
	"\n" +
	"provenance\x18\v \x01(\v2\x1e.sheaf.common.v1.RowProvenanceR\n" +
	"provenance*k\n" +
	"\fDocClaimKind\x12\x1e\n" +
	"\x1aDOC_CLAIM_KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREFERENCE\x10\x01\x12\x11\n" +
	"\rPROSE_MENTION\x10\x02\x12\v\n" +
	"\aEXAMPLE\x10\x03\x12\f\n" +
	"\bWORKFLOW\x10\x04B,Z*github.com/sheaf-data/sheaf/proto/docclaimb\x06proto3"

var (
	file_doc_claim_proto_rawDescOnce sync.Once
	file_doc_claim_proto_rawDescData []byte
)

func file_doc_claim_proto_rawDescGZIP() []byte {
	file_doc_claim_proto_rawDescOnce.Do(func() {
		file_doc_claim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doc_claim_proto_rawDesc), len(file_doc_claim_proto_rawDesc)))
	})
	return file_doc_claim_proto_rawDescData
}

var file_doc_claim_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_doc_claim_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_doc_claim_proto_goTypes = []any{
	(DocClaimKind)(0),             // 0: sheaf.docclaim.v1.DocClaimKind
	(*DocClaim)(nil),              // 1: sheaf.docclaim.v1.DocClaim
	(*common.SourceLocation)(nil), // 2: sheaf.common.v1.SourceLocation
	(common.Substance)(0),         // 3: sheaf.common.v1.Substance
	(*common.RowProvenance)(nil),  // 4: sheaf.common.v1.RowProvenance
}
var file_doc_claim_proto_depIdxs = []int32{
	2, // 0: sheaf.docclaim.v1.DocClaim.location:type_name -> sheaf.common.v1.SourceLocation
	3, // 1: sheaf.docclaim.v1.DocClaim.substance:type_name -> sheaf.common.v1.Substance
	0, // 2: sheaf.docclaim.v1.DocClaim.kind:type_name -> sheaf.docclaim.v1.DocClaimKind
	4, // 3: sheaf.docclaim.v1.DocClaim.provenance:type_name -> sheaf.common.v1.RowProvenance
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_doc_claim_proto_init() }
func file_doc_claim_proto_init() {
	if File_doc_claim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doc_claim_proto_rawDesc), len(file_doc_claim_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_doc_claim_proto_goTypes,
		DependencyIndexes: file_doc_claim_proto_depIdxs,
		EnumInfos:         file_doc_claim_proto_enumTypes,
		MessageInfos:      file_doc_claim_proto_msgTypes,
	}.Build()
	File_doc_claim_proto = out.File
	file_doc_claim_proto_goTypes = nil
	file_doc_claim_proto_depIdxs = nil
}
