// Finding — a single gap report emitted by an analyzer.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: finding.proto

package finding

import (
	common "github.com/sheaf-data/sheaf/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindingKind int32

const (
	FindingKind_FINDING_KIND_UNSPECIFIED FindingKind = 0
	FindingKind_DOCUMENTED_UNTESTED      FindingKind = 1
	FindingKind_TESTED_UNDOCUMENTED      FindingKind = 2
	FindingKind_MISSING_IN_CATEGORY      FindingKind = 3
	FindingKind_THIN_REFERENCE           FindingKind = 4
	FindingKind_EXTERNAL_MENTION_ONLY    FindingKind = 5
	FindingKind_COVERAGE_DELTA           FindingKind = 6
	FindingKind_STALE_DOC                FindingKind = 7
)

// Enum value maps for FindingKind.
var (
	FindingKind_name = map[int32]string{
		0: "FINDING_KIND_UNSPECIFIED",
		1: "DOCUMENTED_UNTESTED",
		2: "TESTED_UNDOCUMENTED",
		3: "MISSING_IN_CATEGORY",
		4: "THIN_REFERENCE",
		5: "EXTERNAL_MENTION_ONLY",
		6: "COVERAGE_DELTA",
		7: "STALE_DOC",
	}
	FindingKind_value = map[string]int32{
		"FINDING_KIND_UNSPECIFIED": 0,
		"DOCUMENTED_UNTESTED":      1,
		"TESTED_UNDOCUMENTED":      2,
		"MISSING_IN_CATEGORY":      3,
		"THIN_REFERENCE":           4,
		"EXTERNAL_MENTION_ONLY":    5,
		"COVERAGE_DELTA":           6,
		"STALE_DOC":                7,
	}
)

func (x FindingKind) Enum() *FindingKind {
	p := new(FindingKind)
	*p = x
	return p
}

func (x FindingKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingKind) Descriptor() protoreflect.EnumDescriptor {
	return file_finding_proto_enumTypes[0].Descriptor()
}

func (FindingKind) Type() protoreflect.EnumType {
	return &file_finding_proto_enumTypes[0]
}

func (x FindingKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingKind.Descriptor instead.
func (FindingKind) EnumDescriptor() ([]byte, []int) {
	return file_finding_proto_rawDescGZIP(), []int{0}
}

type EvidencePointer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Location      *common.SourceLocation `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidencePointer) Reset() {
	*x = EvidencePointer{}
	mi := &file_finding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidencePointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidencePointer) ProtoMessage() {}

func (x *EvidencePointer) ProtoReflect() protoreflect.Message {
	mi := &file_finding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidencePointer.ProtoReflect.Descriptor instead.
func (*EvidencePointer) Descriptor() ([]byte, []int) {
	return file_finding_proto_rawDescGZIP(), []int{0}
}

func (x *EvidencePointer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EvidencePointer) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *EvidencePointer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          FindingKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=sheaf.finding.v1.FindingKind" json:"kind,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"` // ContractElement ID or doc path
	Severity      common.Severity        `protobuf:"varint,4,opt,name=severity,proto3,enum=sheaf.common.v1.Severity" json:"severity,omitempty"`
	Evidence      []*EvidencePointer     `protobuf:"bytes,5,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Provenance    *common.Provenance     `protobuf:"bytes,6,opt,name=provenance,proto3" json:"provenance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Analyzer      string                 `protobuf:"bytes,8,opt,name=analyzer,proto3" json:"analyzer,omitempty"` // name of the producing analyzer
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`   // short human-readable summary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_finding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_finding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_finding_proto_rawDescGZIP(), []int{1}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetKind() FindingKind {
	if x != nil {
		return x.Kind
	}
	return FindingKind_FINDING_KIND_UNSPECIFIED
}

func (x *Finding) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Finding) GetSeverity() common.Severity {
	if x != nil {
		return x.Severity
	}
	return common.Severity(0)
}

func (x *Finding) GetEvidence() []*EvidencePointer {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Finding) GetProvenance() *common.Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Finding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Finding) GetAnalyzer() string {
	if x != nil {
		return x.Analyzer
	}
	return ""
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_finding_proto protoreflect.FileDescriptor

const file_finding_proto_rawDesc = "" +
	"\n" +
	"\rfinding.proto\x12\x10sheaf.finding.v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n" +
	"\x0fEvidencePointer\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12;\n" +
	"\blocation\x18\x02 \x01(\v2\x1f.sheaf.common.v1.SourceLocationR\blocation\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x8a\x03\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.sheaf.finding.v1.FindingKindR\x04kind\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x125\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x19.sheaf.common.v1.SeverityR\bseverity\x12=\n" +
	"\bevidence\x18\x05 \x03(\v2!.sheaf.finding.v1.EvidencePointerR\bevidence\x12;\n" +
	"\n" +
	"provenance\x18\x06 \x01(\v2\x1b.sheaf.common.v1.ProvenanceR\n" +
	"provenance\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\banalyzer\x18\b \x01(\tR\banalyzer\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage*\xc8\x01\n" +
	"\vFindingKind\x12\x1c\n" +
	"\x18FINDING_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DOCUMENTED_UNTESTED\x10\x01\x12\x17\n" +
	"\x13TESTED_UNDOCUMENTED\x10\x02\x12\x17\n" +
	"\x13MISSING_IN_CATEGORY\x10\x03\x12\x12\n" +
	"\x0eTHIN_REFERENCE\x10\x04\x12\x19\n" +
	"\x15EXTERNAL_MENTION_ONLY\x10\x05\x12\x12\n" +
	"\x0eCOVERAGE_DELTA\x10\x06\x12\r\n" +
	"\tSTALE_DOC\x10\aB+Z)github.com/sheaf-data/sheaf/proto/findingb\x06proto3"

var (
	file_finding_proto_rawDescOnce sync.Once
	file_finding_proto_rawDescData []byte
)

func file_finding_proto_rawDescGZIP() []byte {
	file_finding_proto_rawDescOnce.Do(func() {
		file_finding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finding_proto_rawDesc), len(file_finding_proto_rawDesc)))
	})
	return file_finding_proto_rawDescData
}

var file_finding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_finding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_finding_proto_goTypes = []any{
	(FindingKind)(0),              // 0: sheaf.finding.v1.FindingKind
	(*EvidencePointer)(nil),       // 1: sheaf.finding.v1.EvidencePointer
	(*Finding)(nil),               // 2: sheaf.finding.v1.Finding
	(*common.SourceLocation)(nil), // 3: sheaf.common.v1.SourceLocation
	(common.Severity)(0),          // 4: sheaf.common.v1.Severity
	(*common.Provenance)(nil),     // 5: sheaf.common.v1.Provenance
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_finding_proto_depIdxs = []int32{
	3, // 0: sheaf.finding.v1.EvidencePointer.location:type_name -> sheaf.common.v1.SourceLocation
	0, // 1: sheaf.finding.v1.Finding.kind:type_name -> sheaf.finding.v1.FindingKind
	4, // 2: sheaf.finding.v1.Finding.severity:type_name -> sheaf.common.v1.Severity
	1, // 3: sheaf.finding.v1.Finding.evidence:type_name -> sheaf.finding.v1.EvidencePointer
	5, // 4: sheaf.finding.v1.Finding.provenance:type_name -> sheaf.common.v1.Provenance
	6, // 5: sheaf.finding.v1.Finding.created_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_finding_proto_init() }
func file_finding_proto_init() {
	if File_finding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finding_proto_rawDesc), len(file_finding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_finding_proto_goTypes,
		DependencyIndexes: file_finding_proto_depIdxs,
		EnumInfos:         file_finding_proto_enumTypes,
		MessageInfos:      file_finding_proto_msgTypes,
	}.Build()
	File_finding_proto = out.File
	file_finding_proto_goTypes = nil
	file_finding_proto_depIdxs = nil
}
