// Package protocpp implements a test-parser adapter for C++ test
// suites whose contract surface is declared in protobuf. Like gtest,
// it walks *_test.cc files for TEST(), TEST_F(), TEST_P() (and
// project-supplied extra macros), but it extracts ContractRefs using
// the idioms protoc's C++ bindings produce — patterns common to envoy,
// grpc, kubernetes, and any other gRPC-shaped C++ codebase. The
// adapter was originally developed to scan envoy's xDS test tree but
// is parameterized by IDLPrefix so it works against any protobuf
// project.
//
// Patterns recognized:
//
//   - String-literal gRPC method-descriptor names:
//     "<prefix>.<pkg>.<Service>.<Method>"
//     gRPC clients look up RPCs by their fully-qualified method name,
//     passed as a quoted string to DescriptorPool::FindMethodByName.
//     These are the only direct textual reference to specific RPCs in
//     C++ test code that uses mocks instead of generated stubs.
//
//   - Fully-qualified C++ proto type references:
//     <prefix>::<pkg>::<TypeName>
//     Generated by protoc from `package <prefix>.<pkg>;`. The bare
//     local name AND the dotted form are both emitted as refs,
//     matching the aliases the proto adapter attaches to TYPE
//     elements.
//
//   - Generated *.pb.h include scope:
//     #include "<prefix>/<pkg>/<basename>.pb.h"
//     Adds the implied package to the file's library scope so
//     unqualified `<TypeName>` references resolve to the right library
//     when only one is in scope.
//
//   - `*_test_harness.h` include following:
//     Test harness headers carry the fixture's descriptor wiring (the
//     FindMethodByName call) used by every test in the .cc; we scan
//     the harness header and propagate its refs to all tests in the
//     including file.
//
//   - Per-test body windows are brace-counted (skipping strings,
//     chars, and // / /* */ comments) so a free-standing helper class
//     defined between two TEST() macros doesn't leak its refs into
//     the surrounding tests.
//
//   - Preamble named-constants (`constexpr char NAME[] = "...";`) only
//     propagate their refs to tests that mention NAME in their body —
//     constants used by some tests don't false-positive every other
//     test in the file.
//
//   - When the adapter finds confident direct-ref evidence on a test
//     (qualified-type or string-literal or harness-derived), it
//     suppresses NameTokens so the indexer's fuzzy name-token
//     attribution (Strategy 2) doesn't add false positives on top.
//
//   - Namespace-scope-aware test-fixture references:
//     namespace <prefix>::<pkg> { TEST(Fixture, …) { ... } }
//     For every TEST / TEST_F / TEST_P / TYPED_TEST / TYPED_TEST_P
//     macro lexically enclosed by a C++ namespace whose leading
//     segment matches idl_prefix, the macro's first argument (the
//     fixture name) is emitted as a bare candidate ref. Pigweed is
//     the canonical case (`namespace pw::rpc { TEST(EchoService, …) }`);
//     parts of gRPC and envoy follow the same convention. The
//     indexer's existing alias-match path joins those bare refs to
//     the right contract element via the short-form alias the proto
//     adapter already emits.
//
// The new patterns are additive — none of the existing fuchsia/grpc
// gtest behavior is affected, because protocpp is a distinct adapter
// selected by name in the textproto.
package protocpp

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/sheaf-data/sheaf/internal/adapters"
	commonpb "github.com/sheaf-data/sheaf/proto/common"
	testcasepb "github.com/sheaf-data/sheaf/proto/testcase"
)

const Name = "protocpp"
const Version = "0.1.0"

// Parser implements adapters.TestParser for proto-shaped C++ tests.
type Parser struct {
	include         []string
	exclude         []string
	extraTestMacros []string
	macroRegex      *regexp.Regexp
	// fixtureRegex is the namespace-scoped-extractor's per-macro regex.
	// It catches `TEST(Fixture, TestName` and the variants listed in
	// the fixture-emitting macro group; the first capture is the
	// fixture name (suite arg). Built per-parser so the macro group
	// can include extra_test_macros.
	fixtureRegex *regexp.Regexp
	// IDLPrefix is the project's idl_prefix (e.g. "envoy"). String- and
	// namespace-based extractors anchor on it so we don't falsely
	// attribute references to std:: or absl:: types.
	idlPrefix string
	// extractCalls enables bare free-function call-site extraction.
	extractCalls bool
}

// Config bundles the per-adapter config from sheaf.textproto.
type Config struct {
	Include         []string
	Exclude         []string
	ExtraTestMacros []string
	// IDLPrefix selects which dotted/namespace prefix anchors body-level
	// reference extraction. Empty falls back to "envoy".
	IDLPrefix string
	// ExtractFreeFunctionCalls opts in to extracting bare free-function
	// call-sites from each test body (`Encode(buf)`) as candidate refs.
	// Off by default; see ProtoCPPConfig.extract_free_function_calls.
	ExtractFreeFunctionCalls bool
}

// New constructs a Parser with the given config.
func New(cfg Config) *Parser {
	prefix := cfg.IDLPrefix
	if prefix == "" {
		prefix = "envoy"
	}
	macros := []string{"TEST", "TEST_F", "TEST_P"}
	macros = append(macros, cfg.ExtraTestMacros...)
	macroAlt := ""
	for i, m := range macros {
		if i > 0 {
			macroAlt += "|"
		}
		macroAlt += regexp.QuoteMeta(m)
	}
	rx := regexp.MustCompile(`(?m)\b(` + macroAlt + `)\s*\(\s*(\w+)\s*,\s*(\w+)\s*[\),]`)
	// fixtureRegex shares the macro alternation. It deliberately
	// requires the first arg to begin with an uppercase letter — the
	// fixture name is always a CamelCase type identifier, and that
	// shape filters out the very rare case where the suite arg is a
	// macro-generated lowercase token.
	fixtureMacros := []string{"TEST", "TEST_F", "TEST_P", "TYPED_TEST", "TYPED_TEST_P"}
	fixtureMacros = append(fixtureMacros, cfg.ExtraTestMacros...)
	fixtureAlt := ""
	for i, m := range fixtureMacros {
		if i > 0 {
			fixtureAlt += "|"
		}
		fixtureAlt += regexp.QuoteMeta(m)
	}
	fixtureRx := regexp.MustCompile(
		`(?m)\b(?:` + fixtureAlt + `)\s*\(\s*([A-Z][A-Za-z0-9_]*)\s*,\s*[A-Z][A-Za-z0-9_]*`)
	include := cfg.Include
	if len(include) == 0 {
		include = []string{
			"**/*_test.cc", "**/*_test.cpp",
			"**/*_tests.cc", "**/*_tests.cpp",
		}
	}
	return &Parser{
		include:         include,
		exclude:         cfg.Exclude,
		extraTestMacros: cfg.ExtraTestMacros,
		macroRegex:      rx,
		fixtureRegex:    fixtureRx,
		idlPrefix:       prefix,
		extractCalls:    cfg.ExtractFreeFunctionCalls,
	}
}

func (p *Parser) Name() string                  { return Name }
func (p *Parser) Version() string               { return Version }
func (p *Parser) SupportedFrameworks() []string { return []string{"gtest"} }

// Discover scans the repo for gtest-style C++ tests that reference
// protobuf-defined contract elements. Context cancellation is honored
// between files.
func (p *Parser) Discover(ctx context.Context, repoRoot string, _ adapters.ScopeConfig) ([]*testcasepb.TestCase, error) {
	stringLitRx := p.stringLiteralRegex()
	qualifiedRx := p.qualifiedTypeRegex()
	pbhIncludeRx := p.pbhIncludeRegex()
	preambleConstRx := p.preambleConstRegex()
	harnessIncludeRx := harnessIncludeRegex
	var out []*testcasepb.TestCase
	// Cache for harness-header refs so we don't re-scan the same header
	// for every test file that includes it.
	harnessCache := map[string][]string{}
	err := adapters.WalkMatching(repoRoot, p.include, p.exclude, func(rel string, _ fs.DirEntry) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		body, err := adapters.ReadFile(repoRoot, rel)
		if err != nil {
			return fmt.Errorf("protocpp: read %s: %w", rel, err)
		}
		lineOffsets := computeLineOffsets(body)
		matches := p.macroRegex.FindAllSubmatchIndex(body, -1)
		bodyStr := string(body)
		// File-level scope from `#include "<pkg>/<basename>.pb.h"`.
		fileScope := extractPBHScope(bodyStr, pbhIncludeRx)
		// Per-file namespace checkpoint table. Cheap to build (one
		// linear pass) and shared by every test in the file via the
		// per-test namespaceAtCheckpoints lookup.
		nsCps := computeNamespaceCheckpoints(bodyStr)

		// Preamble = bytes before the first TEST() macro. Constants and
		// includes declared here are file-level setup; refs from inside
		// a TEST() body belong only to that test.
		preambleEnd := len(body)
		if len(matches) > 0 {
			preambleEnd = matches[0][0]
		}
		preamble := bodyStr[:preambleEnd]

		// Preamble-level named constants:
		//   constexpr char NAME[] = "envoy.x.y.z.Svc.Method";
		// Per-test we'll only inherit a constant's refs when the test
		// body mentions NAME. Fixes the false-positive where tests at
		// the bottom of the file got attributed to constants used by
		// unrelated tests at the top.
		preambleConsts := extractPreambleConsts(preamble, preambleConstRx)

		// Refs from #include "..._test_harness.h" / "..._test_base.h" —
		// gRPC-shaped C++ tests routinely delegate descriptor wiring
		// to a header-only fixture. The harness's `FindMethodByName(...)`
		// drives the actual RPC under test, but the call site never
		// appears in the .cc, so the per-test-body scan would miss it.
		// Cached because many tests share the same harness.
		var harnessRefs []string
		for _, m := range harnessIncludeRx.FindAllStringSubmatch(preamble, -1) {
			inc := m[1]
			resolved := resolveHarnessInclude(repoRoot, rel, inc)
			if resolved == "" {
				continue
			}
			if cached, ok := harnessCache[resolved]; ok {
				harnessRefs = mergeRefs(harnessRefs, cached)
				continue
			}
			refs := scanHarnessHeader(repoRoot, resolved, stringLitRx, qualifiedRx)
			harnessCache[resolved] = refs
			harnessRefs = mergeRefs(harnessRefs, refs)
		}

		for i, m := range matches {
			_ = string(body[m[2]:m[3]]) // macro
			suite := string(body[m[4]:m[5]])
			testName := string(body[m[6]:m[7]])
			line := lineFromOffset(lineOffsets, m[0])
			id := suite + "." + testName
			// Per-test body window: start at the TEST() macro and end at
			// the matching `}` of the test body. Falls back to the start
			// of the next TEST() macro (or EOF) only when brace tracking
			// fails — without this, a TEST followed by a free-standing
			// helper class would attribute the class's body to the test,
			// false-positive-attributing every type the helper mentions.
			rangeStart := m[0]
			rangeEnd := findTestBodyEnd(bodyStr, rangeStart)
			if rangeEnd < 0 {
				rangeEnd = len(body)
				if i+1 < len(matches) {
					rangeEnd = matches[i+1][0]
				}
			}
			testBody := bodyStr[rangeStart:rangeEnd]
			// Per-test extraction.
			testRefs := extractStringLiteralRefs(testBody, stringLitRx)
			testRefs = mergeRefs(testRefs, extractQualifiedTypeRefs(testBody, qualifiedRx))
			// Preamble constants — only inherit when the test mentions
			// the constant by name. preambleConsts is {name: [refs...]}.
			for name, refs := range preambleConsts {
				if strings.Contains(testBody, name) {
					testRefs = mergeRefs(testRefs, refs)
				}
			}
			// Harness-included refs apply to every test in the file:
			// the harness's descriptor wiring is shared by all tests
			// that use the header's fixture class.
			testRefs = mergeRefs(testRefs, harnessRefs)
			// Fold file-level scope into qualified emissions: if test
			// body mentions a bare TypeName that matches the .pb.h
			// includes' packages, emit the dotted form too.
			testRefs = mergeRefs(testRefs, scopeQualifyBareTypes(testBody, fileScope))
			// Namespace-scope-aware fixture ref: if this TEST macro
			// is lexically inside a namespace whose leading segment
			// matches idl_prefix, emit the bare suite name (fixture)
			// as a candidate ref. The indexer's alias-match path
			// joins it to the proto element's short-form alias.
			// Filtering on prefix avoids `namespace foo::bar {
			// TEST(Thing, …) }` in an unrelated namespace.
			if p.idlPrefix != "" {
				ns := namespaceAtCheckpoints(nsCps, m[0])
				if namespaceLeadingSegmentMatches(ns, p.idlPrefix) {
					testRefs = mergeRefs(testRefs, []string{suite})
				}
			}
			// Bare free-function call-sites (opt-in). A test that calls
			// `Encode(buf)` (after a using-declaration brought the function
			// into scope) directly exercises that free function, but the call
			// is neither a string-literal nor a qualified-type ref. Emit the
			// bare call identifier as a candidate; the indexer's exact
			// bare-name alias match resolves it to the real element and drops
			// the identifiers that match nothing.
			if p.extractCalls {
				testRefs = mergeRefs(testRefs, extractFreeFunctionCallRefs(testBody))
			}
			testRefs = dedupSorted(testRefs)
			// NameTokens always populated — the indexer's name-token
			// Strategy 2 fuzzy matcher catches a lot of legitimate
			// attributions for tests whose direct refs live in fixture
			// helpers we can't reach (e.g. envoy's `setup()` in a
			// TEST_F fixture base class). An earlier experiment
			// suppressed NameTokens when direct refs were present, to
			// kill 2 fuzzy-match FPs — but it also lost 40+ legitimate
			// TPs per element, a net loss. Strategy 2 noise is
			// acceptable here.
			nameTokens := tokenizeName(suite + " " + testName)
			testCase := &testcasepb.TestCase{
				Id:        id,
				Framework: "gtest",
				Location: &commonpb.SourceLocation{
					Path: rel,
					Line: uint32(line),
				},
				Name:         id,
				NameTokens:   nameTokens,
				SourceHash:   hashBytes(body[m[0]:m[1]]),
				Assertions:   nil,
				ContractRefs: testRefs,
			}
			out = append(out, testCase)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ----------------------------------------------------------------
// Regex factories — built per-parser so they can be anchored on the
// project's idl_prefix.
// ----------------------------------------------------------------

// stringLiteralRegex matches gRPC method-name string literals shaped
// `"<prefix>.<seg>+.<Service>.<Method>"`. Service and Method are
// CamelCase identifiers; the inner segments are lowercase (or v1/v2alpha).
// Anchored on the IDL prefix so we don't gobble unrelated dotted
// strings like absl-style names.
func (p *Parser) stringLiteralRegex() *regexp.Regexp {
	q := regexp.QuoteMeta(p.idlPrefix)
	return regexp.MustCompile(
		`"(` + q + `(?:\.[a-z][a-z0-9_]*)+(?:\.v[0-9][a-z0-9]*)?\.[A-Z][A-Za-z0-9_]*\.[A-Z][A-Za-z0-9_]*)"`)
}

// qualifiedTypeRegex matches fully-qualified C++ proto type references
// shaped `<prefix>::<seg>+::<TypeName>`. Anchored on idl_prefix; the
// non-prefix-anchored form (matching all of std::, absl::, …) would be
// massively false-positive.
func (p *Parser) qualifiedTypeRegex() *regexp.Regexp {
	q := regexp.QuoteMeta(p.idlPrefix)
	return regexp.MustCompile(
		`\b` + q + `(?:::[a-z][a-z0-9_]*)+(?:::v[0-9][a-z0-9]*)?::([A-Z][A-Za-z0-9_]*)\b`)
}

// pbhIncludeRegex matches `#include "<pkg-path>/<basename>.pb.h"` and
// captures the package path (slash form). The .pb.h suffix is the
// canonical generated-cc header from protoc, and is unique enough to
// not need IDL-prefix anchoring (a file that includes .pb.h is using
// proto-generated types).
func (p *Parser) pbhIncludeRegex() *regexp.Regexp {
	return regexp.MustCompile(
		`#include\s+[<"]([a-z][a-z0-9_/]*)/[a-z][a-z0-9_]*\.pb\.h[>"]`)
}

// preambleConstRegex matches a named C/C++ const string literal whose
// value is a dotted IDL identifier, e.g.:
//
//	constexpr char kAdsMethod[] = "envoy.service.discovery.v3.AggregatedDiscoveryService.StreamAggregatedResources";
//	const char kFoo[] = "envoy.x.y.z.Svc.Method";
//	static constexpr absl::string_view kBar = "envoy....";
//
// Captures (1) the constant's identifier and (2) the dotted RPC string.
// Anchored on idl_prefix the same way stringLiteralRegex is.
//
// NB: the regex once had an optional namespace-like prefix written as
// `(?:[a-zA-Z_][a-zA-Z0-9_]*)?` that backtrack-greedy-matched part of
// the constant name (e.g. captured just "d" out of "kAdsMethod"),
// making every test body containing the letter "d" inherit the const's
// refs. The current form requires the optional prefix to end with `::`
// so it can only match real C++ namespace tokens like `absl::`.
func (p *Parser) preambleConstRegex() *regexp.Regexp {
	q := regexp.QuoteMeta(p.idlPrefix)
	return regexp.MustCompile(
		`(?:constexpr|static\s+constexpr|const|static\s+const)\s+` +
			`(?:[a-zA-Z_][a-zA-Z0-9_]*::)*` + // optional C++ namespace prefix on the TYPE only
			`(?:char|string_view|string)\s+` +
			`([a-zA-Z_][A-Za-z0-9_]*)` + // (1) constant name
			`(?:\s*\[\s*\])?\s*=\s*` +
			`"(` + q + `(?:\.[a-z][a-z0-9_]*)+(?:\.v[0-9][a-z0-9]*)?\.[A-Z][A-Za-z0-9_]*\.[A-Z][A-Za-z0-9_]*)"`)
}

// harnessIncludeRegex matches `#include "..._test_harness.h"` ONLY.
// Envoy's xDS test files put their descriptor wiring in headers named
// with this exact suffix (subscription_test_harness.h,
// grpc_subscription_test_harness.h, http_subscription_test_harness.h,
// delta_subscription_test_harness.h, filesystem_subscription_test_harness.h).
// Without following them, the per-test body scan misses the
// `FindMethodByName("envoy.x.y.Svc.Method")` calls that drive the RPC
// under test.
//
// NB: an earlier version also matched `_test_base.h`, `_integration_test.h`,
// and `_fixture.h`. Those patterns are too broad — generic scaffolds
// like `base_integration_test.h` contain 30+ xDS descriptor refs as
// helper machinery, and following them attributed every TCP/HTTP/ext_proc
// test that #included the base class to those descriptors as a false
// positive. The narrow `_test_harness.h` suffix is sheaf-specific
// enough to be a strong signal.
//
// Pattern-agnostic to idl_prefix because the harness naming convention
// is project-organization, not a proto identifier.
var harnessIncludeRegex = regexp.MustCompile(
	`#include\s+"([^"]*_test_harness\.h)"`)

// ----------------------------------------------------------------
// Extractors.
// ----------------------------------------------------------------

// extractStringLiteralRefs returns the captured ref strings (already in
// the dotted form the proto adapter uses as an alias for METHOD
// elements). For each "<lib>.<Service>.<Method>" hit we also emit the
// parent "<lib>.<Service>" form — a test that names a method as a gRPC
// method-descriptor string is also exercising the service the method
// belongs to, and sheaf's proto adapter aliases the PROTOCOL element
// under that dotted form. Without parent emission, scanner reports a
// false negative for the service even though every method it owns has
// attributed tests.
func extractStringLiteralRefs(body string, rx *regexp.Regexp) []string {
	matches := rx.FindAllStringSubmatch(body, -1)
	if len(matches) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(matches)*2)
	out := make([]string, 0, len(matches)*2)
	for _, m := range matches {
		full := m[1]
		if _, ok := seen[full]; !ok {
			seen[full] = struct{}{}
			out = append(out, full)
		}
		if dot := strings.LastIndexByte(full, '.'); dot > 0 {
			parent := full[:dot]
			if _, ok := seen[parent]; !ok {
				seen[parent] = struct{}{}
				out = append(out, parent)
			}
		}
	}
	return out
}

// extractQualifiedTypeRefs walks every <prefix>::<seg>+::<TypeName>
// reference in body and emits both the dotted-package form (matches the
// TYPE element's fully-qualified alias) and the bare local form
// (matches the TYPE element's bare alias). The bare alias is ambiguous
// across packages; the indexer's exact-match step filters it back to
// the right element when only one TYPE has that name.
func extractQualifiedTypeRefs(body string, rx *regexp.Regexp) []string {
	matches := rx.FindAllStringSubmatchIndex(body, -1)
	if len(matches) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(matches)*2)
	out := make([]string, 0, len(matches)*2)
	for _, m := range matches {
		full := body[m[0]:m[1]]
		name := body[m[2]:m[3]]
		// Drop the trailing "::<name>" to recover the namespace, then
		// turn "::" into "." for the dotted package.
		nsCpp := strings.TrimSuffix(full, "::"+name)
		pkg := strings.ReplaceAll(nsCpp, "::", ".")
		dotted := pkg + "." + name
		if _, ok := seen[dotted]; !ok {
			seen[dotted] = struct{}{}
			out = append(out, dotted)
		}
		if _, ok := seen[name]; !ok {
			seen[name] = struct{}{}
			out = append(out, name)
		}
	}
	return out
}

// bareCallRx matches a BARE function call: an identifier directly followed by
// `(`, NOT preceded by a member/scope operator (`.`, `->`, `::`) or another
// identifier character. This deliberately skips qualified calls
// (`pw::varint::Encode(` — already handled by extractQualifiedTypeRefs) and
// member calls (`sb.append(`, `p->Frob(`), capturing only unqualified
// free-function call-sites like `Encode(` that a using-declaration brought
// into scope.
var bareCallRx = regexp.MustCompile(`(?:^|[^A-Za-z0-9_.>:])([A-Za-z_][A-Za-z0-9_]*)\s*\(`)

// callKeyword holds lowercase C++ control-flow / cast / operator keywords that
// can appear as `keyword(` but are never contract elements.
var callKeyword = map[string]bool{
	"if": true, "for": true, "while": true, "switch": true, "return": true,
	"catch": true, "sizeof": true, "alignof": true, "alignas": true,
	"decltype": true, "noexcept": true, "static_assert": true, "throw": true,
	"static_cast": true, "reinterpret_cast": true, "const_cast": true,
	"dynamic_cast": true, "and": true, "or": true, "not": true, "do": true,
	"else": true, "case": true, "new": true, "delete": true, "operator": true,
}

// extractFreeFunctionCallRefs returns the distinct bare free-function call
// identifiers in a test body, minus macros and keywords. Two cheap, general
// filters keep this honest (correctness over coverage):
//
//   - SCREAMING_CASE identifiers are dropped — every gtest/Pigweed test &
//     assertion macro (TEST, EXPECT_EQ, PW_CONSTEXPR_TEST, PW_TEST_ASSERT_OK)
//     and integer-suffix macro (UINT32_C) is all-caps, while C++ free
//     functions are Camel/snake case. One rule, no per-project macro list.
//   - lowercase C++ keywords (if/for/sizeof/static_cast/…) are dropped.
//
// Everything surviving is a CANDIDATE ref; the indexer's exact bare-name alias
// match resolves it to the real element and silently drops identifiers (local
// test helpers, std calls) that name no contract element.
func extractFreeFunctionCallRefs(body string) []string {
	matches := bareCallRx.FindAllStringSubmatch(body, -1)
	if len(matches) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(matches))
	out := make([]string, 0, len(matches))
	for _, m := range matches {
		id := m[1]
		if isScreamingMacro(id) || callKeyword[id] {
			continue
		}
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	return out
}

// isScreamingMacro reports whether s is an ALL-CAPS (+ digits / underscores)
// identifier with at least one letter — the C macro convention. Any lowercase
// letter disqualifies it, so Camel/snake-case function names are kept.
func isScreamingMacro(s string) bool {
	hasUpper := false
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'a' && c <= 'z' {
			return false
		}
		if c >= 'A' && c <= 'Z' {
			hasUpper = true
		}
	}
	return hasUpper
}

// extractPBHScope returns the set of proto packages a file pulls in via
// generated `.pb.h` includes. Path "envoy/service/discovery/v3" maps to
// package "envoy.service.discovery.v3".
func extractPBHScope(body string, rx *regexp.Regexp) map[string]struct{} {
	out := map[string]struct{}{}
	for _, m := range rx.FindAllStringSubmatch(body, -1) {
		pkg := strings.ReplaceAll(m[1], "/", ".")
		out[pkg] = struct{}{}
	}
	return out
}

// extractPreambleConsts returns {const_name: [refs]} for every named
// const-string declaration in the preamble whose value is a dotted IDL
// identifier. Refs include both the matched RPC and its parent service
// (same emission rule as extractStringLiteralRefs).
//
// Callers use this with a per-test "does the test body mention
// const_name?" check so a constant used by only some tests doesn't
// false-positive every other test in the file.
func extractPreambleConsts(preamble string, rx *regexp.Regexp) map[string][]string {
	out := map[string][]string{}
	for _, m := range rx.FindAllStringSubmatch(preamble, -1) {
		name := m[1]
		full := m[2]
		refs, ok := out[name]
		if !ok {
			refs = []string{}
		}
		// Same parent-service emission as extractStringLiteralRefs.
		if !contains(refs, full) {
			refs = append(refs, full)
		}
		if dot := strings.LastIndexByte(full, '.'); dot > 0 {
			parent := full[:dot]
			if !contains(refs, parent) {
				refs = append(refs, parent)
			}
		}
		out[name] = refs
	}
	return out
}

// ----------------------------------------------------------------
// Namespace-scope-aware fixture extractor.
//
// Tracks C++ namespace scope through the file so that tests written
// inside `namespace pw::rpc { TEST(EchoService, …) }` get the bare
// fixture name "EchoService" emitted as a candidate ref. The indexer's
// existing alias-match path (Strategy 1) joins those bare refs to the
// proto-element's short-form alias without any indexer-side change.
// ----------------------------------------------------------------

// nsCheckpoint records the namespace stack in effect starting at a
// given byte offset. `stack` is the dotted segments (e.g.
// ["pw","rpc"]) in outer-to-inner order. Anonymous namespaces are
// transparent — they don't appear in `stack` even though they push a
// brace frame on the scope stack.
type nsCheckpoint struct {
	offset int
	stack  []string
}

// namespaceAt returns the current C++ namespace as a dotted path
// (e.g. "pw.rpc") for the byte offset `at` in body. Returns "" when
// no namespace is open or only anonymous namespaces enclose the
// position.
//
// The tracker handles:
//   - `namespace foo { ... }`               nested form
//   - `namespace foo::bar::baz { ... }`     C++17 nested name
//   - `namespace { ... }`                   anonymous (transparent)
//   - `using namespace foo;`                ignored
//   - `namespace foo = bar;`                ignored (alias)
//   - matching closing brace counting       block scope
//
// String literals, char literals, and // / /* */ comments are
// stripped so `"} namespace fake {"` and `// }` don't fool the brace
// counter. Preprocessor `#ifdef` around namespace decls is not
// specially handled — that pattern is rare in test files.
func namespaceAt(body string, at int) string {
	return namespaceAtCheckpoints(computeNamespaceCheckpoints(body), at)
}

// namespaceAtCheckpoints binary-searches `cps` for the last checkpoint
// whose offset <= at and returns its stack as a dotted path.
func namespaceAtCheckpoints(cps []nsCheckpoint, at int) string {
	if len(cps) == 0 {
		return ""
	}
	lo, hi := 0, len(cps)-1
	for lo < hi {
		mid := (lo + hi + 1) / 2
		if cps[mid].offset <= at {
			lo = mid
		} else {
			hi = mid - 1
		}
	}
	if cps[lo].offset > at {
		return ""
	}
	return strings.Join(cps[lo].stack, ".")
}

// computeNamespaceCheckpoints does one pass over body and returns the
// sorted checkpoint list. Every `{` pushes a brace frame; every `}`
// pops one. Namespace-introducing constructs additionally record their
// declared segments on the pushed frame.
func computeNamespaceCheckpoints(body string) []nsCheckpoint {
	type frame struct{ segs []string }
	var frames []frame

	flatten := func() []string {
		// Pre-size for the common case.
		size := 0
		for _, f := range frames {
			size += len(f.segs)
		}
		if size == 0 {
			return nil
		}
		out := make([]string, 0, size)
		for _, f := range frames {
			out = append(out, f.segs...)
		}
		return out
	}

	cps := []nsCheckpoint{{offset: 0, stack: nil}}
	appendCp := func(off int) {
		s := flatten()
		last := cps[len(cps)-1]
		if stringSliceEqual(last.stack, s) {
			// Anonymous-ns push or non-ns block — no path change.
			return
		}
		// If the previous checkpoint is at the same offset, overwrite
		// (e.g. nested push-pop at one position).
		if last.offset == off {
			cps[len(cps)-1] = nsCheckpoint{offset: off, stack: s}
			return
		}
		cps = append(cps, nsCheckpoint{offset: off, stack: s})
	}

	n := len(body)
	i := 0
	for i < n {
		c := body[i]
		switch {
		case c == '/' && i+1 < n && body[i+1] == '/':
			// Line comment.
			j := i + 2
			for j < n && body[j] != '\n' {
				j++
			}
			i = j
		case c == '/' && i+1 < n && body[i+1] == '*':
			// Block comment.
			j := i + 2
			for j+1 < n && !(body[j] == '*' && body[j+1] == '/') {
				j++
			}
			if j+1 < n {
				i = j + 2
			} else {
				i = n
			}
		case c == '"':
			// String literal — skip to closing quote, honoring escapes.
			j := i + 1
			for j < n && body[j] != '"' {
				if body[j] == '\\' && j+1 < n {
					j += 2
					continue
				}
				j++
			}
			i = j + 1
		case c == '\'':
			// Char literal.
			j := i + 1
			for j < n && body[j] != '\'' {
				if body[j] == '\\' && j+1 < n {
					j += 2
					continue
				}
				j++
			}
			i = j + 1
		case c == '{':
			// Non-namespace block. Push an empty frame; no path change.
			frames = append(frames, frame{segs: nil})
			i++
		case c == '}':
			if len(frames) > 0 {
				top := frames[len(frames)-1]
				frames = frames[:len(frames)-1]
				if len(top.segs) > 0 {
					appendCp(i + 1)
				}
			}
			i++
		case isIdentStart(c) && wordEqual(body, i, "namespace"):
			// Could be:
			//   `using namespace foo;`  — handled by lookahead (no `{`).
			//   `namespace foo = bar;`  — handled by lookahead (no `{`).
			//   `namespace { ... }`     — anonymous, push empty frame.
			//   `namespace foo[::bar]* { ... }` — push named frame.
			end := i + len("namespace")
			j := skipWSAndComments(body, end)
			if j >= n {
				i = end
				continue
			}
			if body[j] == '{' {
				// Anonymous namespace — push transparent frame.
				frames = append(frames, frame{segs: nil})
				i = j + 1
				continue
			}
			if isIdentStart(body[j]) {
				// Parse ident(::ident)*
				var segs []string
				k := j
				for k < n && isIdentStart(body[k]) {
					start := k
					for k < n && isIdentCont(body[k]) {
						k++
					}
					segs = append(segs, body[start:k])
					kk := skipWSAndComments(body, k)
					if kk+1 < n && body[kk] == ':' && body[kk+1] == ':' {
						k = skipWSAndComments(body, kk+2)
						continue
					}
					k = kk
					break
				}
				k = skipWSAndComments(body, k)
				if k < n && body[k] == '{' {
					frames = append(frames, frame{segs: segs})
					appendCp(k + 1)
					i = k + 1
					continue
				}
				// Not a namespace block — alias, decl, or noise.
				// Resume scanning after the parsed identifier chain.
				i = k
				continue
			}
			i = end
		default:
			i++
		}
	}
	return cps
}

// extractNamespaceScopedFixtureRefs returns bare candidate refs for
// every test macro whose enclosing namespace's leading segment equals
// idlPrefix. The returned refs are the bare fixture name only (e.g.
// "EchoService"), unqualified; the indexer's alias matcher joins them
// against the right element via the proto adapter's short-form alias.
//
// Returns nil if idlPrefix is empty — the matcher requires an anchor
// to filter out unrelated namespaces.
func extractNamespaceScopedFixtureRefs(body, idlPrefix string, extraMacros []string) []string {
	if idlPrefix == "" {
		return nil
	}
	fixtureMacros := []string{"TEST", "TEST_F", "TEST_P", "TYPED_TEST", "TYPED_TEST_P"}
	fixtureMacros = append(fixtureMacros, extraMacros...)
	alt := ""
	for i, m := range fixtureMacros {
		if i > 0 {
			alt += "|"
		}
		alt += regexp.QuoteMeta(m)
	}
	rx := regexp.MustCompile(
		`(?m)\b(?:` + alt + `)\s*\(\s*([A-Z][A-Za-z0-9_]*)\s*,\s*[A-Z][A-Za-z0-9_]*`)
	cps := computeNamespaceCheckpoints(body)
	seen := map[string]struct{}{}
	var out []string
	for _, m := range rx.FindAllStringSubmatchIndex(body, -1) {
		ns := namespaceAtCheckpoints(cps, m[0])
		if !namespaceLeadingSegmentMatches(ns, idlPrefix) {
			continue
		}
		fixture := body[m[2]:m[3]]
		if _, ok := seen[fixture]; !ok {
			seen[fixture] = struct{}{}
			out = append(out, fixture)
		}
	}
	return out
}

// namespaceLeadingSegmentMatches reports whether the first dotted
// segment of ns equals prefix. ns is the dotted form returned by
// namespaceAt ("pw.rpc"); prefix is the project's bare idl_prefix
// ("pw"). Both empty inputs return false (no anchor → no match).
func namespaceLeadingSegmentMatches(ns, prefix string) bool {
	if ns == "" || prefix == "" {
		return false
	}
	if ns == prefix {
		return true
	}
	return strings.HasPrefix(ns, prefix+".")
}

// skipWSAndComments returns the smallest index >= i pointing at a
// byte that is neither whitespace nor inside a comment.
func skipWSAndComments(body string, i int) int {
	n := len(body)
	for i < n {
		c := body[i]
		switch {
		case c == ' ' || c == '\t' || c == '\n' || c == '\r':
			i++
		case c == '/' && i+1 < n && body[i+1] == '/':
			j := i + 2
			for j < n && body[j] != '\n' {
				j++
			}
			i = j
		case c == '/' && i+1 < n && body[i+1] == '*':
			j := i + 2
			for j+1 < n && !(body[j] == '*' && body[j+1] == '/') {
				j++
			}
			if j+1 < n {
				i = j + 2
			} else {
				i = n
			}
		default:
			return i
		}
	}
	return i
}

func isIdentStart(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
}

func isIdentCont(c byte) bool {
	return isIdentStart(c) || (c >= '0' && c <= '9')
}

// wordEqual reports whether body[at:at+len(word)] == word and that the
// match is word-bounded (no ident character immediately before or
// after).
func wordEqual(body string, at int, word string) bool {
	if at+len(word) > len(body) {
		return false
	}
	if body[at:at+len(word)] != word {
		return false
	}
	if at+len(word) < len(body) && isIdentCont(body[at+len(word)]) {
		return false
	}
	if at > 0 && isIdentCont(body[at-1]) {
		return false
	}
	return true
}

func stringSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// resolveHarnessInclude turns an `#include "..."` quoted path into a
// repo-relative path. Tries two resolutions in order:
//  1. relative to the including file's directory (closer C++ semantics)
//  2. relative to the repo root (envoy's bazel-style absolute includes)
//
// Returns "" if neither file exists.
func resolveHarnessInclude(repoRoot, includingRel, incPath string) string {
	// Drop leading `./` if present.
	incPath = strings.TrimPrefix(incPath, "./")
	candidates := []string{
		filepath.ToSlash(filepath.Join(filepath.Dir(includingRel), incPath)),
		incPath,
	}
	for _, c := range candidates {
		full := filepath.Join(repoRoot, c)
		if info, err := os.Stat(full); err == nil && !info.IsDir() {
			return c
		}
	}
	return ""
}

// scanHarnessHeader reads a harness header and extracts string-literal
// + qualified-type refs, applying the same parent-service emission
// rule. Used to surface descriptor wiring (FindMethodByName(...)) that
// lives in the header but drives every test in the .cc.
func scanHarnessHeader(repoRoot, rel string, stringLitRx, qualifiedRx *regexp.Regexp) []string {
	body, err := os.ReadFile(filepath.Join(repoRoot, rel))
	if err != nil {
		return nil
	}
	bs := string(body)
	refs := extractStringLiteralRefs(bs, stringLitRx)
	refs = mergeRefs(refs, extractQualifiedTypeRefs(bs, qualifiedRx))
	return refs
}

func contains(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

// findTestBodyEnd returns the byte offset just past the closing `}` of
// the test body that starts at or after `start`. Tracks brace depth
// while skipping over string/char literals and // / /* */ comments so
// braces inside those don't confuse the count. Returns -1 if no
// matching brace is found within 200 KB (caller falls back to the next
// TEST() macro).
//
// Without this, the per-test body window for a TEST that's followed by
// a free-standing helper class would include the helper's body —
// every type or string literal the helper mentions would attribute to
// the test as a false positive.
func findTestBodyEnd(body string, start int) int {
	const maxScan = 200 * 1024
	end := start + maxScan
	if end > len(body) {
		end = len(body)
	}
	// Find the opening `{` of the test body. The TEST macro args end at
	// the closing `)`; skip ahead to the first `{`.
	i := start
	depth := 0
	for i < end {
		switch body[i] {
		case '{':
			depth++
			i++
			goto scan
		default:
			i++
		}
	}
	return -1
scan:
	for i < end {
		c := body[i]
		switch c {
		case '{':
			depth++
			i++
		case '}':
			depth--
			i++
			if depth == 0 {
				return i
			}
		case '/':
			if i+1 < end && body[i+1] == '/' {
				// Line comment — skip to end of line.
				j := i + 2
				for j < end && body[j] != '\n' {
					j++
				}
				i = j
			} else if i+1 < end && body[i+1] == '*' {
				// Block comment — skip to matching */.
				j := i + 2
				for j+1 < end && !(body[j] == '*' && body[j+1] == '/') {
					j++
				}
				if j+1 < end {
					j += 2
				} else {
					j = end
				}
				i = j
			} else {
				i++
			}
		case '"':
			// String literal — skip to closing quote, honoring escapes.
			j := i + 1
			for j < end && body[j] != '"' {
				if body[j] == '\\' && j+1 < end {
					j += 2
					continue
				}
				j++
			}
			i = j + 1
		case '\'':
			// Char literal — same as string but typically short.
			j := i + 1
			for j < end && body[j] != '\'' {
				if body[j] == '\\' && j+1 < end {
					j += 2
					continue
				}
				j++
			}
			i = j + 1
		default:
			i++
		}
	}
	return -1
}

// scopeQualifyBareTypes scans body for bare CamelCase identifiers used
// in C++-fixture-style declarations and, for each one, emits the
// dotted-package alias `<pkg>.<Type>` for every package in scope. Used
// to catch references that omit the C++ namespace because of a
// `using envoy::service::discovery::v3::DiscoveryRequest;` (or just
// shorter writing) but still resolve via the file's .pb.h includes.
//
// Conservative: matches only the
//
//	`<Type> <varname>(;|=|{|()`
//
// fixture shape (same as gtest's gtestFixtureRx) so we don't dump every
// capitalized identifier in scope × pkg. The bare-type alias the proto
// adapter attaches to each TYPE element is the fallback path; this is
// the per-file pkg-disambiguation overlay.
// Suffix list includes the standard proto-message conventions plus
// "Dummy" — envoy uses *Dummy types (AdsDummy, CdsDummy, LedsDummy, …)
// as placeholder messages for service-bearing proto files that have no
// data messages of their own.
var bareFixtureRx = regexp.MustCompile(
	`(?m)^\s*([A-Z][A-Za-z0-9_]+(?:Request|Response|Message|Event|Trace|State|Data|Ref|Info|Config|Options?|Resource|Locator|Name|Error|Dummy))\s+[a-z_][A-Za-z0-9_]*\s*[;=({]`)

func scopeQualifyBareTypes(body string, scope map[string]struct{}) []string {
	if len(scope) == 0 {
		return nil
	}
	matches := bareFixtureRx.FindAllStringSubmatch(body, -1)
	if len(matches) == 0 {
		return nil
	}
	seen := map[string]struct{}{}
	var out []string
	for _, m := range matches {
		name := m[1]
		if _, ok := seen[name]; !ok {
			seen[name] = struct{}{}
			out = append(out, name)
		}
		for pkg := range scope {
			dotted := pkg + "." + name
			if _, ok := seen[dotted]; !ok {
				seen[dotted] = struct{}{}
				out = append(out, dotted)
			}
		}
	}
	return out
}

// ----------------------------------------------------------------
// Helpers borrowed in spirit from the gtest adapter.
// ----------------------------------------------------------------

func computeLineOffsets(body []byte) []int {
	offsets := []int{0}
	for i, b := range body {
		if b == '\n' {
			offsets = append(offsets, i+1)
		}
	}
	return offsets
}

func lineFromOffset(offsets []int, off int) int {
	lo, hi := 0, len(offsets)-1
	for lo < hi {
		mid := (lo + hi + 1) / 2
		if offsets[mid] <= off {
			lo = mid
		} else {
			hi = mid - 1
		}
	}
	return lo + 1
}

func hashBytes(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}

func mergeRefs(a, b []string) []string {
	if len(a) == 0 {
		return b
	}
	if len(b) == 0 {
		return a
	}
	seen := make(map[string]struct{}, len(a)+len(b))
	out := make([]string, 0, len(a)+len(b))
	for _, s := range a {
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	for _, s := range b {
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	return out
}

func dedupSorted(s []string) []string {
	if len(s) == 0 {
		return s
	}
	seen := make(map[string]struct{}, len(s))
	out := make([]string, 0, len(s))
	for _, v := range s {
		if _, ok := seen[v]; ok {
			continue
		}
		seen[v] = struct{}{}
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

func tokenizeName(s string) []string {
	var tokens []string
	var cur []rune
	flush := func() {
		if len(cur) > 0 {
			tokens = append(tokens, string(cur))
			cur = cur[:0]
		}
	}
	for i, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			if i > 0 && len(cur) > 0 {
				last := cur[len(cur)-1]
				if last >= 'a' && last <= 'z' {
					flush()
				}
			}
			cur = append(cur, r+('a'-'A'))
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			cur = append(cur, r)
		default:
			flush()
		}
	}
	flush()
	return tokens
}
