// Common types used across Sheaf protos.
//
// Source-location, provenance, references. Everything in here is
// schema-stable across v1; future changes are additive.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Substance is the grading scale for documentation depth.
type Substance int32

const (
	Substance_SUBSTANCE_UNSPECIFIED Substance = 0
	Substance_ABSENT                Substance = 1
	Substance_SIGNATURE_ONLY        Substance = 2
	Substance_PARTIAL               Substance = 3
	Substance_SUBSTANTIVE           Substance = 4
)

// Enum value maps for Substance.
var (
	Substance_name = map[int32]string{
		0: "SUBSTANCE_UNSPECIFIED",
		1: "ABSENT",
		2: "SIGNATURE_ONLY",
		3: "PARTIAL",
		4: "SUBSTANTIVE",
	}
	Substance_value = map[string]int32{
		"SUBSTANCE_UNSPECIFIED": 0,
		"ABSENT":                1,
		"SIGNATURE_ONLY":        2,
		"PARTIAL":               3,
		"SUBSTANTIVE":           4,
	}
)

func (x Substance) Enum() *Substance {
	p := new(Substance)
	*p = x
	return p
}

func (x Substance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Substance) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Substance) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Substance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Substance.Descriptor instead.
func (Substance) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Severity used in analyzer findings.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_INFO                 Severity = 1
	Severity_WARNING              Severity = 2
	Severity_ERROR                Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"INFO":                 1,
		"WARNING":              2,
		"ERROR":                3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type RowProvenance_Tier int32

const (
	RowProvenance_TIER_UNSPECIFIED RowProvenance_Tier = 0
	RowProvenance_DETERMINISTIC    RowProvenance_Tier = 1 // schema/grammar adapter; reproducible, high trust
	RowProvenance_LLM              RowProvenance_Tier = 2 // LLM judgment; citation-verified, recall-unverified
)

// Enum value maps for RowProvenance_Tier.
var (
	RowProvenance_Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "DETERMINISTIC",
		2: "LLM",
	}
	RowProvenance_Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"DETERMINISTIC":    1,
		"LLM":              2,
	}
)

func (x RowProvenance_Tier) Enum() *RowProvenance_Tier {
	p := new(RowProvenance_Tier)
	*p = x
	return p
}

func (x RowProvenance_Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RowProvenance_Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (RowProvenance_Tier) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x RowProvenance_Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RowProvenance_Tier.Descriptor instead.
func (RowProvenance_Tier) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2, 0}
}

// SourceLocation pins a piece of data to a file/line/column in the repo.
type SourceLocation struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Path   string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`      // repo-relative; forward-slash separated
	Line   uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`     // 1-based; 0 means "unknown line"
	Column uint32                 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"` // 1-based; 0 means "unknown column"
	// Canonical clickable URL for the source. Adapters that have a
	// stable per-element URL pattern (e.g. workflows with `url_base`,
	// markdowncli with `url_base`) populate this; otherwise renderers
	// fall back to expanding their --source-url-template against path.
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocation) Reset() {
	*x = SourceLocation{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocation) ProtoMessage() {}

func (x *SourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocation.ProtoReflect.Descriptor instead.
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *SourceLocation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SourceLocation) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourceLocation) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *SourceLocation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Provenance captures who/what/when produced a piece of data.
type Provenance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommitHash      string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	GeneratedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	LlmCallId       string                 `protobuf:"bytes,3,opt,name=llm_call_id,json=llmCallId,proto3" json:"llm_call_id,omitempty"`                                                                                           // empty if no LLM was involved
	AdapterVersions map[string]string      `protobuf:"bytes,4,rep,name=adapter_versions,json=adapterVersions,proto3" json:"adapter_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // adapter name -> version string
	ScanId          string                 `protobuf:"bytes,5,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`                                                                                                      // ties together a single scan run
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Provenance) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *Provenance) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *Provenance) GetLlmCallId() string {
	if x != nil {
		return x.LlmCallId
	}
	return ""
}

func (x *Provenance) GetAdapterVersions() map[string]string {
	if x != nil {
		return x.AdapterVersions
	}
	return nil
}

func (x *Provenance) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

// RowProvenance records HOW a single element / attribution edge entered
// the corpus: which TIER produced it (a deterministic schema/grammar
// adapter vs an LLM judgment under propose/verify), the concrete SOURCE,
// and — for LLM rows only — a TRANSFORM tag from a small fixed taxonomy.
//
// This is per-ROW provenance, distinct from the scan-level Provenance
// above (which captures commit/scan-id/timestamp for a whole run). It is
// the enabling plumbing for two things: the two-tier confidence report
// (deterministic rows vs LLM-inferred rows must never be conflated) and
// the auto-generated sheaf-hardening.md (a GROUP-BY over LLM rows ranked
// by the deterministic replacement that would pin them).
type RowProvenance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tier  RowProvenance_Tier     `protobuf:"varint,1,opt,name=tier,proto3,enum=sheaf.common.v1.RowProvenance_Tier" json:"tier,omitempty"`
	// source is the adapter name for deterministic rows (e.g. "cppheader",
	// "proto") or "llm" for LLM-tier rows.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// transform is set ONLY on LLM rows and names the deterministic
	// replacement that could pin this row. Small fixed taxonomy (drives
	// the hardening doc's GROUP-BY):
	//
	//	"schema-available"          a generator exists for this surface
	//	"macro-alias"               reached via a #define alias/expansion
	//	"syntax-form-regex-misses"  e.g. `using X = MACRO;`, inline constexpr
	//	"indirect-dispatch"         runtime/reflective; likely irreducible
	//	"grouping"                  a logical roll-up the agent decided
	//
	// WORKFLOW-composition rows (DocClaim{kind=WORKFLOW}, tier=LLM, from
	// internal/workflowextract) classify the SOURCE grammar of the
	// extracted sequence so sheaf-hardening.md can GROUP-BY and rank the
	// deterministic replacement that would pin them:
	//
	//	"workflow-cli-grammar"      sequence expressed as `<binary> <subcmd>`
	//	                            command fences → wire the `workflows`
	//	                            rendered-reference adapter (rung 2)
	//	"workflow-yaml-grammar"     sequence in fenced/`.. code-block:: yaml`
	//	                            naming >=2 dotted FQDNs → wire the
	//	                            `yaml-workflows` adapter (rung 1)
	//	"workflow-prose"            free prose, no parseable grammar →
	//	                            likely the irreducible tail (rung 4)
	//
	// Empty on deterministic rows.
	Transform     string `protobuf:"bytes,3,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowProvenance) Reset() {
	*x = RowProvenance{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowProvenance) ProtoMessage() {}

func (x *RowProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowProvenance.ProtoReflect.Descriptor instead.
func (*RowProvenance) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *RowProvenance) GetTier() RowProvenance_Tier {
	if x != nil {
		return x.Tier
	}
	return RowProvenance_TIER_UNSPECIFIED
}

func (x *RowProvenance) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RowProvenance) GetTransform() string {
	if x != nil {
		return x.Transform
	}
	return ""
}

// DocRef is a reference from a doc artifact to a contract element.
// Used as nested entries inside CoverageProfile.DocCoverage.
type DocRef struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Path      string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Line      uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Url       string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"` // canonical published URL, if known
	Substance Substance              `protobuf:"varint,4,opt,name=substance,proto3,enum=sheaf.common.v1.Substance" json:"substance,omitempty"`
	Words     uint32                 `protobuf:"varint,5,opt,name=words,proto3" json:"words,omitempty"`    // word count of the behavioral prose
	Adapter   string                 `protobuf:"bytes,6,opt,name=adapter,proto3" json:"adapter,omitempty"` // adapter that produced this ref
	// provenance tags the edge's tier. Deterministic for refs the
	// cross-reference join produced; LLM for refs an LLM attribution pass
	// proposed and a citation gate confirmed. The trusted coverage number
	// counts deterministic refs only; LLM refs render in the flagged tier.
	// `line` is the cited evidence line for LLM refs.
	Provenance    *RowProvenance `protobuf:"bytes,7,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocRef) Reset() {
	*x = DocRef{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocRef) ProtoMessage() {}

func (x *DocRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocRef.ProtoReflect.Descriptor instead.
func (*DocRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *DocRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DocRef) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *DocRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DocRef) GetSubstance() Substance {
	if x != nil {
		return x.Substance
	}
	return Substance_SUBSTANCE_UNSPECIFIED
}

func (x *DocRef) GetWords() uint32 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *DocRef) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *DocRef) GetProvenance() *RowProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

// TestRef is a reference from a test to a contract element.
type TestRef struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Path      string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Line      uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`                        // for LLM refs, the cited line that references the element
	TestName  string                 `protobuf:"bytes,3,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"` // canonical test ID like "FooTest.Bar"
	Exercises string                 `protobuf:"bytes,4,opt,name=exercises,proto3" json:"exercises,omitempty"`               // contract element ID
	Framework string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`               // "gtest" | "rust-test" | "bats" | ...
	// provenance tags the edge's tier (deterministic join vs citation-
	// gated LLM attribution). See DocRef.provenance.
	Provenance    *RowProvenance `protobuf:"bytes,6,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRef) Reset() {
	*x = TestRef{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRef) ProtoMessage() {}

func (x *TestRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRef.ProtoReflect.Descriptor instead.
func (*TestRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *TestRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TestRef) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *TestRef) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *TestRef) GetExercises() string {
	if x != nil {
		return x.Exercises
	}
	return ""
}

func (x *TestRef) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *TestRef) GetProvenance() *RowProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

// CodeRef is a reference from example code to a contract element.
type CodeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	StartLine     uint32                 `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       uint32                 `protobuf:"varint,3,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	Intent        string                 `protobuf:"bytes,4,opt,name=intent,proto3" json:"intent,omitempty"` // free-form: "tutorial step", "test helper", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeRef) Reset() {
	*x = CodeRef{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeRef) ProtoMessage() {}

func (x *CodeRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeRef.ProtoReflect.Descriptor instead.
func (*CodeRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *CodeRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CodeRef) GetStartLine() uint32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *CodeRef) GetEndLine() uint32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *CodeRef) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

// UsageAggregate summarizes a count of usage sites with sample paths.
type UsageAggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	SamplePaths   []string               `protobuf:"bytes,2,rep,name=sample_paths,json=samplePaths,proto3" json:"sample_paths,omitempty"` // capped; typically 5-10 entries
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageAggregate) Reset() {
	*x = UsageAggregate{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageAggregate) ProtoMessage() {}

func (x *UsageAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageAggregate.ProtoReflect.Descriptor instead.
func (*UsageAggregate) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *UsageAggregate) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UsageAggregate) GetSamplePaths() []string {
	if x != nil {
		return x.SamplePaths
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0fsheaf.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x0eSourceLocation\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\rR\x06column\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\xc6\x02\n" +
	"\n" +
	"Provenance\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12=\n" +
	"\fgenerated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12\x1e\n" +
	"\vllm_call_id\x18\x03 \x01(\tR\tllmCallId\x12[\n" +
	"\x10adapter_versions\x18\x04 \x03(\v20.sheaf.common.v1.Provenance.AdapterVersionsEntryR\x0fadapterVersions\x12\x17\n" +
	"\ascan_id\x18\x05 \x01(\tR\x06scanId\x1aB\n" +
	"\x14AdapterVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\rRowProvenance\x127\n" +
	"\x04tier\x18\x01 \x01(\x0e2#.sheaf.common.v1.RowProvenance.TierR\x04tier\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1c\n" +
	"\ttransform\x18\x03 \x01(\tR\ttransform\"8\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rDETERMINISTIC\x10\x01\x12\a\n" +
	"\x03LLM\x10\x02\"\xec\x01\n" +
	"\x06DocRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x128\n" +
	"\tsubstance\x18\x04 \x01(\x0e2\x1a.sheaf.common.v1.SubstanceR\tsubstance\x12\x14\n" +
	"\x05words\x18\x05 \x01(\rR\x05words\x12\x18\n" +
	"\aadapter\x18\x06 \x01(\tR\aadapter\x12>\n" +
	"\n" +
	"provenance\x18\a \x01(\v2\x1e.sheaf.common.v1.RowProvenanceR\n" +
	"provenance\"\xca\x01\n" +
	"\aTestRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x1b\n" +
	"\ttest_name\x18\x03 \x01(\tR\btestName\x12\x1c\n" +
	"\texercises\x18\x04 \x01(\tR\texercises\x12\x1c\n" +
	"\tframework\x18\x05 \x01(\tR\tframework\x12>\n" +
	"\n" +
	"provenance\x18\x06 \x01(\v2\x1e.sheaf.common.v1.RowProvenanceR\n" +
	"provenance\"o\n" +
	"\aCodeRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"start_line\x18\x02 \x01(\rR\tstartLine\x12\x19\n" +
	"\bend_line\x18\x03 \x01(\rR\aendLine\x12\x16\n" +
	"\x06intent\x18\x04 \x01(\tR\x06intent\"I\n" +
	"\x0eUsageAggregate\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12!\n" +
	"\fsample_paths\x18\x02 \x03(\tR\vsamplePaths*d\n" +
	"\tSubstance\x12\x19\n" +
	"\x15SUBSTANCE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ABSENT\x10\x01\x12\x12\n" +
	"\x0eSIGNATURE_ONLY\x10\x02\x12\v\n" +
	"\aPARTIAL\x10\x03\x12\x0f\n" +
	"\vSUBSTANTIVE\x10\x04*F\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03B*Z(github.com/sheaf-data/sheaf/proto/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_proto_goTypes = []any{
	(Substance)(0),                // 0: sheaf.common.v1.Substance
	(Severity)(0),                 // 1: sheaf.common.v1.Severity
	(RowProvenance_Tier)(0),       // 2: sheaf.common.v1.RowProvenance.Tier
	(*SourceLocation)(nil),        // 3: sheaf.common.v1.SourceLocation
	(*Provenance)(nil),            // 4: sheaf.common.v1.Provenance
	(*RowProvenance)(nil),         // 5: sheaf.common.v1.RowProvenance
	(*DocRef)(nil),                // 6: sheaf.common.v1.DocRef
	(*TestRef)(nil),               // 7: sheaf.common.v1.TestRef
	(*CodeRef)(nil),               // 8: sheaf.common.v1.CodeRef
	(*UsageAggregate)(nil),        // 9: sheaf.common.v1.UsageAggregate
	nil,                           // 10: sheaf.common.v1.Provenance.AdapterVersionsEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	11, // 0: sheaf.common.v1.Provenance.generated_at:type_name -> google.protobuf.Timestamp
	10, // 1: sheaf.common.v1.Provenance.adapter_versions:type_name -> sheaf.common.v1.Provenance.AdapterVersionsEntry
	2,  // 2: sheaf.common.v1.RowProvenance.tier:type_name -> sheaf.common.v1.RowProvenance.Tier
	0,  // 3: sheaf.common.v1.DocRef.substance:type_name -> sheaf.common.v1.Substance
	5,  // 4: sheaf.common.v1.DocRef.provenance:type_name -> sheaf.common.v1.RowProvenance
	5,  // 5: sheaf.common.v1.TestRef.provenance:type_name -> sheaf.common.v1.RowProvenance
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
