// ContractElement and Relationship — the addressable units of an API surface.
//
// Every adapter that parses contract sources emits values of these types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: contract.proto

package contract

import (
	common "github.com/sheaf-data/sheaf/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractElementKind enumerates the kinds of addressable items Sheaf
// recognizes on a contract surface. Adapters map their native concepts
// to one of these.
type ContractElementKind int32

const (
	ContractElementKind_KIND_UNSPECIFIED ContractElementKind = 0
	ContractElementKind_METHOD           ContractElementKind = 1
	ContractElementKind_FLAG             ContractElementKind = 2
	ContractElementKind_SUBCOMMAND       ContractElementKind = 3
	ContractElementKind_TYPE             ContractElementKind = 4 // FIDL struct/table/union/enum/bits
	ContractElementKind_SYSCALL          ContractElementKind = 5
	ContractElementKind_POSITIONAL       ContractElementKind = 6
	ContractElementKind_SWITCH           ContractElementKind = 7
	ContractElementKind_PROTOCOL         ContractElementKind = 8  // FIDL protocol as a first-class element
	ContractElementKind_CPP_CLASS        ContractElementKind = 9  // C++ class used as IMPLEMENTS target
	ContractElementKind_RUST_TYPE        ContractElementKind = 10 // Rust struct/enum/trait used similarly
	ContractElementKind_LIBRARY          ContractElementKind = 11 // A whole library / namespace, as a synthetic element.
	// Used to attach library-level metadata (e.g. an
	// @available annotation that deprecates the entire
	// surface) to a single addressable record. ID is
	// the bare library name (no "/").
	ContractElementKind_CONFIG_KNOB ContractElementKind = 12 // A persistent configuration setting declared by a
	// contract surface — e.g. a field in a Fuchsia
	// structured-config block in a .cml file, or an
	// argh CLI flag whose annotation includes
	// `default = "..."` (signalling it represents
	// persistent state rather than a per-invocation
	// input).
	ContractElementKind_CONFIG_FACET ContractElementKind = 13 // One of multiple declarations of the same logical
	// config knob (env var + CLI flag + config-file
	// key for the same setting). Reserved for the
	// cross-source matching (SAME_AFFORDANCE) pass;
	// not emitted by single-source adapters in v1.
	ContractElementKind_CPP_MACRO         ContractElementKind = 14 // C++ #define-style API entry (e.g. PW_LOG_DEBUG).
	ContractElementKind_CPP_FREE_FUNCTION ContractElementKind = 15 // C++ free function not attached to a class.
	ContractElementKind_CPP_METHOD        ContractElementKind = 16 // C++ member function declared inside a class/struct.
	ContractElementKind_CPP_ENUM          ContractElementKind = 17 // C++ enum / enum class declared in a header.
)

// Enum value maps for ContractElementKind.
var (
	ContractElementKind_name = map[int32]string{
		0:  "KIND_UNSPECIFIED",
		1:  "METHOD",
		2:  "FLAG",
		3:  "SUBCOMMAND",
		4:  "TYPE",
		5:  "SYSCALL",
		6:  "POSITIONAL",
		7:  "SWITCH",
		8:  "PROTOCOL",
		9:  "CPP_CLASS",
		10: "RUST_TYPE",
		11: "LIBRARY",
		12: "CONFIG_KNOB",
		13: "CONFIG_FACET",
		14: "CPP_MACRO",
		15: "CPP_FREE_FUNCTION",
		16: "CPP_METHOD",
		17: "CPP_ENUM",
	}
	ContractElementKind_value = map[string]int32{
		"KIND_UNSPECIFIED":  0,
		"METHOD":            1,
		"FLAG":              2,
		"SUBCOMMAND":        3,
		"TYPE":              4,
		"SYSCALL":           5,
		"POSITIONAL":        6,
		"SWITCH":            7,
		"PROTOCOL":          8,
		"CPP_CLASS":         9,
		"RUST_TYPE":         10,
		"LIBRARY":           11,
		"CONFIG_KNOB":       12,
		"CONFIG_FACET":      13,
		"CPP_MACRO":         14,
		"CPP_FREE_FUNCTION": 15,
		"CPP_METHOD":        16,
		"CPP_ENUM":          17,
	}
)

func (x ContractElementKind) Enum() *ContractElementKind {
	p := new(ContractElementKind)
	*p = x
	return p
}

func (x ContractElementKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractElementKind) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[0].Descriptor()
}

func (ContractElementKind) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[0]
}

func (x ContractElementKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractElementKind.Descriptor instead.
func (ContractElementKind) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

type RelationshipKind int32

const (
	RelationshipKind_RELATIONSHIP_UNSPECIFIED RelationshipKind = 0
	RelationshipKind_COMPOSED_FROM            RelationshipKind = 1
	RelationshipKind_COMPOSED_BY              RelationshipKind = 2
	RelationshipKind_INHERITED_FROM           RelationshipKind = 3
	RelationshipKind_ACCEPTS_TYPE             RelationshipKind = 4
	RelationshipKind_RETURNS_TYPE             RelationshipKind = 5
	RelationshipKind_REFERENCES_TYPE          RelationshipKind = 6
	RelationshipKind_IMPLEMENTS               RelationshipKind = 7
	RelationshipKind_IMPLEMENTED_BY           RelationshipKind = 8
	RelationshipKind_REPLACED_BY              RelationshipKind = 9
	RelationshipKind_REPLACES                 RelationshipKind = 10
	RelationshipKind_ALIASES                  RelationshipKind = 11
	RelationshipKind_SAME_AFFORDANCE          RelationshipKind = 12 // Two ContractElement rows represent the same
	// underlying capability reached through different
	// declaration surfaces (e.g. a CONFIG_KNOB in a
	// .cml + a CONFIG_KNOB from an argh option with
	// default, both named the same and same type).
	// Emitted by the affordance matcher pass; carries
	// a confidence score on the Relationship message.
	RelationshipKind_FACET_OF RelationshipKind = 13 // A directional refinement of SAME_AFFORDANCE: the
	// source element is one facet of the target's
	// canonical declaration. Reserved for v2 when the
	// matcher learns to pick a canonical side
	// (e.g. `.cml` over a generated env var binding).
	// v1 matcher emits SAME_AFFORDANCE only.
	RelationshipKind_SAME_AS RelationshipKind = 14 // Bidirectional identity link between contract
)

// Enum value maps for RelationshipKind.
var (
	RelationshipKind_name = map[int32]string{
		0:  "RELATIONSHIP_UNSPECIFIED",
		1:  "COMPOSED_FROM",
		2:  "COMPOSED_BY",
		3:  "INHERITED_FROM",
		4:  "ACCEPTS_TYPE",
		5:  "RETURNS_TYPE",
		6:  "REFERENCES_TYPE",
		7:  "IMPLEMENTS",
		8:  "IMPLEMENTED_BY",
		9:  "REPLACED_BY",
		10: "REPLACES",
		11: "ALIASES",
		12: "SAME_AFFORDANCE",
		13: "FACET_OF",
		14: "SAME_AS",
	}
	RelationshipKind_value = map[string]int32{
		"RELATIONSHIP_UNSPECIFIED": 0,
		"COMPOSED_FROM":            1,
		"COMPOSED_BY":              2,
		"INHERITED_FROM":           3,
		"ACCEPTS_TYPE":             4,
		"RETURNS_TYPE":             5,
		"REFERENCES_TYPE":          6,
		"IMPLEMENTS":               7,
		"IMPLEMENTED_BY":           8,
		"REPLACED_BY":              9,
		"REPLACES":                 10,
		"ALIASES":                  11,
		"SAME_AFFORDANCE":          12,
		"FACET_OF":                 13,
		"SAME_AS":                  14,
	}
)

func (x RelationshipKind) Enum() *RelationshipKind {
	p := new(RelationshipKind)
	*p = x
	return p
}

func (x RelationshipKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationshipKind) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[1].Descriptor()
}

func (RelationshipKind) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[1]
}

func (x RelationshipKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationshipKind.Descriptor instead.
func (RelationshipKind) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

// A directed relationship from this ContractElement to another.
// Only the outbound direction is stored; the indexer materializes
// the inverse at load time.
type Relationship struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            RelationshipKind       `protobuf:"varint,1,opt,name=kind,proto3,enum=sheaf.contract.v1.RelationshipKind" json:"kind,omitempty"`
	TargetElementId string                 `protobuf:"bytes,2,opt,name=target_element_id,json=targetElementId,proto3" json:"target_element_id,omitempty"`
	Note            string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	DeclarationSite *common.SourceLocation `protobuf:"bytes,4,opt,name=declaration_site,json=declarationSite,proto3" json:"declaration_site,omitempty"`
	// Match confidence in [0, 1]. Only meaningful for relationship
	// kinds whose source is heuristic — currently SAME_AFFORDANCE and
	// FACET_OF. Structural relationships (COMPOSED_FROM, IMPLEMENTS,
	// ACCEPTS_TYPE, …) leave this at zero; they're either present or
	// absent, never partial. Above-threshold relationships are
	// returned in default agent-facing queries; below-threshold go to
	// the anomaly stream for human review (F8.17 separation).
	Confidence    float64 `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Relationship) GetKind() RelationshipKind {
	if x != nil {
		return x.Kind
	}
	return RelationshipKind_RELATIONSHIP_UNSPECIFIED
}

func (x *Relationship) GetTargetElementId() string {
	if x != nil {
		return x.TargetElementId
	}
	return ""
}

func (x *Relationship) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Relationship) GetDeclarationSite() *common.SourceLocation {
	if x != nil {
		return x.DeclarationSite
	}
	return nil
}

func (x *Relationship) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Parameter of a method/syscall/subcommand.
type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeRef       string                 `protobuf:"bytes,2,opt,name=type_ref,json=typeRef,proto3" json:"type_ref,omitempty"` // free-form type reference, ecosystem-specific
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetTypeRef() string {
	if x != nil {
		return x.TypeRef
	}
	return ""
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Parameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

// TypeRef points at another ContractElement (typically a TYPE kind).
type TypeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementId     string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Display       string                 `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"` // human-readable rendering of the type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRef) Reset() {
	*x = TypeRef{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRef) ProtoMessage() {}

func (x *TypeRef) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRef.ProtoReflect.Descriptor instead.
func (*TypeRef) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *TypeRef) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *TypeRef) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

// VersionConstraint expresses an availability constraint
// (FIDL @available, Rust #[cfg(feature = ...)], etc.).
type VersionConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ecosystem     string                 `protobuf:"bytes,1,opt,name=ecosystem,proto3" json:"ecosystem,omitempty"`
	Added         string                 `protobuf:"bytes,2,opt,name=added,proto3" json:"added,omitempty"` // version where this element first appeared
	Deprecated    string                 `protobuf:"bytes,3,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	Removed       string                 `protobuf:"bytes,4,opt,name=removed,proto3" json:"removed,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionConstraint) Reset() {
	*x = VersionConstraint{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionConstraint) ProtoMessage() {}

func (x *VersionConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionConstraint.ProtoReflect.Descriptor instead.
func (*VersionConstraint) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *VersionConstraint) GetEcosystem() string {
	if x != nil {
		return x.Ecosystem
	}
	return ""
}

func (x *VersionConstraint) GetAdded() string {
	if x != nil {
		return x.Added
	}
	return ""
}

func (x *VersionConstraint) GetDeprecated() string {
	if x != nil {
		return x.Deprecated
	}
	return ""
}

func (x *VersionConstraint) GetRemoved() string {
	if x != nil {
		return x.Removed
	}
	return ""
}

func (x *VersionConstraint) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// ContractElement — the central addressable unit.
type ContractElement struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // canonical ID, ecosystem-specific format
	Kind               ContractElementKind    `protobuf:"varint,2,opt,name=kind,proto3,enum=sheaf.contract.v1.ContractElementKind" json:"kind,omitempty"`
	Ecosystem          string                 `protobuf:"bytes,3,opt,name=ecosystem,proto3" json:"ecosystem,omitempty"` // "fidl" | "argh" | "cpp" | "rust" | ...
	Library            string                 `protobuf:"bytes,4,opt,name=library,proto3" json:"library,omitempty"`
	Location           *common.SourceLocation `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Parameters         []*Parameter           `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ReturnTypes        []*TypeRef             `protobuf:"bytes,7,rep,name=return_types,json=returnTypes,proto3" json:"return_types,omitempty"`
	DocCommentExcerpt  string                 `protobuf:"bytes,8,opt,name=doc_comment_excerpt,json=docCommentExcerpt,proto3" json:"doc_comment_excerpt,omitempty"` // raw /// or argh description text
	VersionConstraints []*VersionConstraint   `protobuf:"bytes,9,rep,name=version_constraints,json=versionConstraints,proto3" json:"version_constraints,omitempty"`
	Relationships      []*Relationship        `protobuf:"bytes,10,rep,name=relationships,proto3" json:"relationships,omitempty"`
	EcosystemMeta      *structpb.Struct       `protobuf:"bytes,11,opt,name=ecosystem_meta,json=ecosystemMeta,proto3" json:"ecosystem_meta,omitempty"`
	// Alternate IDs that name the same element. Used for CLI aliases
	// (e.g. `docker container ls` aliases ["docker container list",
	// "docker container ps", "docker ps"]). The indexer consults
	// these when matching tests/docs whose tokens line up with an
	// alias's form rather than the canonical ID.
	Aliases []string `protobuf:"bytes,12,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// provenance records which tier (deterministic adapter vs LLM)
	// produced this element. Drives the two-tier report and the
	// hardening doc. Unset implies deterministic for back-compat with
	// adapters that predate provenance threading.
	Provenance    *common.RowProvenance `protobuf:"bytes,13,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractElement) Reset() {
	*x = ContractElement{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractElement) ProtoMessage() {}

func (x *ContractElement) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractElement.ProtoReflect.Descriptor instead.
func (*ContractElement) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ContractElement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContractElement) GetKind() ContractElementKind {
	if x != nil {
		return x.Kind
	}
	return ContractElementKind_KIND_UNSPECIFIED
}

func (x *ContractElement) GetEcosystem() string {
	if x != nil {
		return x.Ecosystem
	}
	return ""
}

func (x *ContractElement) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *ContractElement) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ContractElement) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ContractElement) GetReturnTypes() []*TypeRef {
	if x != nil {
		return x.ReturnTypes
	}
	return nil
}

func (x *ContractElement) GetDocCommentExcerpt() string {
	if x != nil {
		return x.DocCommentExcerpt
	}
	return ""
}

func (x *ContractElement) GetVersionConstraints() []*VersionConstraint {
	if x != nil {
		return x.VersionConstraints
	}
	return nil
}

func (x *ContractElement) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *ContractElement) GetEcosystemMeta() *structpb.Struct {
	if x != nil {
		return x.EcosystemMeta
	}
	return nil
}

func (x *ContractElement) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ContractElement) GetProvenance() *common.RowProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\x11sheaf.contract.v1\x1a\fcommon.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf3\x01\n" +
	"\fRelationship\x127\n" +
	"\x04kind\x18\x01 \x01(\x0e2#.sheaf.contract.v1.RelationshipKindR\x04kind\x12*\n" +
	"\x11target_element_id\x18\x02 \x01(\tR\x0ftargetElementId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12J\n" +
	"\x10declaration_site\x18\x04 \x01(\v2\x1f.sheaf.common.v1.SourceLocationR\x0fdeclarationSite\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\"\x9d\x01\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\btype_ref\x18\x02 \x01(\tR\atypeRef\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\"B\n" +
	"\aTypeRef\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\"\x95\x01\n" +
	"\x11VersionConstraint\x12\x1c\n" +
	"\tecosystem\x18\x01 \x01(\tR\tecosystem\x12\x14\n" +
	"\x05added\x18\x02 \x01(\tR\x05added\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x03 \x01(\tR\n" +
	"deprecated\x12\x18\n" +
	"\aremoved\x18\x04 \x01(\tR\aremoved\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"\xb7\x05\n" +
	"\x0fContractElement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x04kind\x18\x02 \x01(\x0e2&.sheaf.contract.v1.ContractElementKindR\x04kind\x12\x1c\n" +
	"\tecosystem\x18\x03 \x01(\tR\tecosystem\x12\x18\n" +
	"\alibrary\x18\x04 \x01(\tR\alibrary\x12;\n" +
	"\blocation\x18\x05 \x01(\v2\x1f.sheaf.common.v1.SourceLocationR\blocation\x12<\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2\x1c.sheaf.contract.v1.ParameterR\n" +
	"parameters\x12=\n" +
	"\freturn_types\x18\a \x03(\v2\x1a.sheaf.contract.v1.TypeRefR\vreturnTypes\x12.\n" +
	"\x13doc_comment_excerpt\x18\b \x01(\tR\x11docCommentExcerpt\x12U\n" +
	"\x13version_constraints\x18\t \x03(\v2$.sheaf.contract.v1.VersionConstraintR\x12versionConstraints\x12E\n" +
	"\rrelationships\x18\n" +
	" \x03(\v2\x1f.sheaf.contract.v1.RelationshipR\rrelationships\x12>\n" +
	"\x0eecosystem_meta\x18\v \x01(\v2\x17.google.protobuf.StructR\recosystemMeta\x12\x18\n" +
	"\aaliases\x18\f \x03(\tR\aaliases\x12>\n" +
	"\n" +
	"provenance\x18\r \x01(\v2\x1e.sheaf.common.v1.RowProvenanceR\n" +
	"provenance*\xa4\x02\n" +
	"\x13ContractElementKind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06METHOD\x10\x01\x12\b\n" +
	"\x04FLAG\x10\x02\x12\x0e\n" +
	"\n" +
	"SUBCOMMAND\x10\x03\x12\b\n" +
	"\x04TYPE\x10\x04\x12\v\n" +
	"\aSYSCALL\x10\x05\x12\x0e\n" +
	"\n" +
	"POSITIONAL\x10\x06\x12\n" +
	"\n" +
	"\x06SWITCH\x10\a\x12\f\n" +
	"\bPROTOCOL\x10\b\x12\r\n" +
	"\tCPP_CLASS\x10\t\x12\r\n" +
	"\tRUST_TYPE\x10\n" +
	"\x12\v\n" +
	"\aLIBRARY\x10\v\x12\x0f\n" +
	"\vCONFIG_KNOB\x10\f\x12\x10\n" +
	"\fCONFIG_FACET\x10\r\x12\r\n" +
	"\tCPP_MACRO\x10\x0e\x12\x15\n" +
	"\x11CPP_FREE_FUNCTION\x10\x0f\x12\x0e\n" +
	"\n" +
	"CPP_METHOD\x10\x10\x12\f\n" +
	"\bCPP_ENUM\x10\x11*\xa1\x02\n" +
	"\x10RelationshipKind\x12\x1c\n" +
	"\x18RELATIONSHIP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCOMPOSED_FROM\x10\x01\x12\x0f\n" +
	"\vCOMPOSED_BY\x10\x02\x12\x12\n" +
	"\x0eINHERITED_FROM\x10\x03\x12\x10\n" +
	"\fACCEPTS_TYPE\x10\x04\x12\x10\n" +
	"\fRETURNS_TYPE\x10\x05\x12\x13\n" +
	"\x0fREFERENCES_TYPE\x10\x06\x12\x0e\n" +
	"\n" +
	"IMPLEMENTS\x10\a\x12\x12\n" +
	"\x0eIMPLEMENTED_BY\x10\b\x12\x0f\n" +
	"\vREPLACED_BY\x10\t\x12\f\n" +
	"\bREPLACES\x10\n" +
	"\x12\v\n" +
	"\aALIASES\x10\v\x12\x13\n" +
	"\x0fSAME_AFFORDANCE\x10\f\x12\f\n" +
	"\bFACET_OF\x10\r\x12\v\n" +
	"\aSAME_AS\x10\x0eB,Z*github.com/sheaf-data/sheaf/proto/contractb\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_contract_proto_goTypes = []any{
	(ContractElementKind)(0),      // 0: sheaf.contract.v1.ContractElementKind
	(RelationshipKind)(0),         // 1: sheaf.contract.v1.RelationshipKind
	(*Relationship)(nil),          // 2: sheaf.contract.v1.Relationship
	(*Parameter)(nil),             // 3: sheaf.contract.v1.Parameter
	(*TypeRef)(nil),               // 4: sheaf.contract.v1.TypeRef
	(*VersionConstraint)(nil),     // 5: sheaf.contract.v1.VersionConstraint
	(*ContractElement)(nil),       // 6: sheaf.contract.v1.ContractElement
	(*common.SourceLocation)(nil), // 7: sheaf.common.v1.SourceLocation
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(*common.RowProvenance)(nil),  // 9: sheaf.common.v1.RowProvenance
}
var file_contract_proto_depIdxs = []int32{
	1,  // 0: sheaf.contract.v1.Relationship.kind:type_name -> sheaf.contract.v1.RelationshipKind
	7,  // 1: sheaf.contract.v1.Relationship.declaration_site:type_name -> sheaf.common.v1.SourceLocation
	0,  // 2: sheaf.contract.v1.ContractElement.kind:type_name -> sheaf.contract.v1.ContractElementKind
	7,  // 3: sheaf.contract.v1.ContractElement.location:type_name -> sheaf.common.v1.SourceLocation
	3,  // 4: sheaf.contract.v1.ContractElement.parameters:type_name -> sheaf.contract.v1.Parameter
	4,  // 5: sheaf.contract.v1.ContractElement.return_types:type_name -> sheaf.contract.v1.TypeRef
	5,  // 6: sheaf.contract.v1.ContractElement.version_constraints:type_name -> sheaf.contract.v1.VersionConstraint
	2,  // 7: sheaf.contract.v1.ContractElement.relationships:type_name -> sheaf.contract.v1.Relationship
	8,  // 8: sheaf.contract.v1.ContractElement.ecosystem_meta:type_name -> google.protobuf.Struct
	9,  // 9: sheaf.contract.v1.ContractElement.provenance:type_name -> sheaf.common.v1.RowProvenance
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		EnumInfos:         file_contract_proto_enumTypes,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
