// Adapter plugin protocol — the wire contract between sheaf and an
// out-of-process ("runtime") adapter.
//
// An external adapter is any executable that speaks this protocol over
// stdio. The host (sheaf) spawns the executable once per Discover call,
// writes a single length-prefixed DiscoverRequest to the child's stdin,
// reads a single length-prefixed DiscoverResponse from its stdout, and
// the child exits. Framing is a 4-byte big-endian length followed by the
// binary-marshaled message. See docs/adapter-protocol.md for the full
// lifecycle, framing, and security model.
//
// The output rows ARE the existing corpus types (ContractElement /
// TestCase / DocClaim), so an external adapter produces exactly what an
// in-process adapter produces — the schema is the contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: adapterplugin.proto

package adapterplugin

import (
	contract "github.com/sheaf-data/sheaf/proto/contract"
	docclaim "github.com/sheaf-data/sheaf/proto/docclaim"
	testcase "github.com/sheaf-data/sheaf/proto/testcase"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role identifies which adapter interface the host is invoking. An
// external adapter may implement more than one role; the request names
// the role for this call, and the response populates only the matching
// output field(s).
type Role int32

const (
	Role_ROLE_UNSPECIFIED        Role = 0
	Role_ROLE_CONTRACT_ANCHOR    Role = 1 // emits ContractElements (and optionally inline DocClaims)
	Role_ROLE_TEST_PARSER        Role = 2 // emits TestCases
	Role_ROLE_DOC_PARSER         Role = 3 // emits DocClaims
	Role_ROLE_RENDERED_REFERENCE Role = 4 // emits DocClaims from a pre-rendered bundle
	Role_ROLE_IMPLEMENTS_MAP     Role = 5 // emits ContractElements (implementing classes)
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_CONTRACT_ANCHOR",
		2: "ROLE_TEST_PARSER",
		3: "ROLE_DOC_PARSER",
		4: "ROLE_RENDERED_REFERENCE",
		5: "ROLE_IMPLEMENTS_MAP",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":        0,
		"ROLE_CONTRACT_ANCHOR":    1,
		"ROLE_TEST_PARSER":        2,
		"ROLE_DOC_PARSER":         3,
		"ROLE_RENDERED_REFERENCE": 4,
		"ROLE_IMPLEMENTS_MAP":     5,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_adapterplugin_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_adapterplugin_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_adapterplugin_proto_rawDescGZIP(), []int{0}
}

// Scope mirrors internal/adapters.ScopeConfig on the wire: the subset of
// project scope an adapter needs to limit its discovery.
type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Library       []string               `protobuf:"bytes,1,rep,name=library,proto3" json:"library,omitempty"` // primary libraries; empty means no filter
	AlsoInclude   []string               `protobuf:"bytes,2,rep,name=also_include,json=alsoInclude,proto3" json:"also_include,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_adapterplugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_adapterplugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_adapterplugin_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetLibrary() []string {
	if x != nil {
		return x.Library
	}
	return nil
}

func (x *Scope) GetAlsoInclude() []string {
	if x != nil {
		return x.AlsoInclude
	}
	return nil
}

func (x *Scope) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

// AdapterConfig is the per-adapter configuration handed to the plugin.
// include/exclude are first-class because nearly every adapter takes
// file globs; everything else rides in the string-keyed `option` map
// (e.g. {"binary_name": "docker"}). This is the host's
// ExternalAdapterConfig projected onto the wire.
type AdapterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Option        map[string]string      `protobuf:"bytes,3,rep,name=option,proto3" json:"option,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterConfig) Reset() {
	*x = AdapterConfig{}
	mi := &file_adapterplugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterConfig) ProtoMessage() {}

func (x *AdapterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_adapterplugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterConfig.ProtoReflect.Descriptor instead.
func (*AdapterConfig) Descriptor() ([]byte, []int) {
	return file_adapterplugin_proto_rawDescGZIP(), []int{1}
}

func (x *AdapterConfig) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *AdapterConfig) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *AdapterConfig) GetOption() map[string]string {
	if x != nil {
		return x.Option
	}
	return nil
}

// DiscoverRequest is the single message the host writes to the plugin's
// stdin. Exactly one is sent per spawn.
type DiscoverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version is the version the host speaks. A plugin MUST reject
	// a request whose version it does not implement (see ProtocolVersion in
	// internal/adapterplugin).
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Role            Role   `protobuf:"varint,2,opt,name=role,proto3,enum=sheaf.adapterplugin.v1.Role" json:"role,omitempty"`
	// repo_path is the absolute path to the repository the plugin should
	// scan. The plugin reads files directly from the local filesystem.
	// Empty for ROLE_RENDERED_REFERENCE, which reads bundle paths from config.
	RepoPath      string         `protobuf:"bytes,3,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	Scope         *Scope         `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Config        *AdapterConfig `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_adapterplugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapterplugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_adapterplugin_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *DiscoverRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *DiscoverRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *DiscoverRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *DiscoverRequest) GetConfig() *AdapterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// DiscoverResponse is the single message the plugin writes to its stdout.
// Exactly one is sent per spawn. The plugin populates the output field(s)
// matching the request role; a contract anchor MAY populate both
// `elements` and `doc_claims` (the DiscoverWithDocs entry point).
type DiscoverResponse struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	ProtocolVersion uint32                      `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Elements        []*contract.ContractElement `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	Tests           []*testcase.TestCase        `protobuf:"bytes,3,rep,name=tests,proto3" json:"tests,omitempty"`
	DocClaims       []*docclaim.DocClaim        `protobuf:"bytes,4,rep,name=doc_claims,json=docClaims,proto3" json:"doc_claims,omitempty"`
	// error, when non-empty, marks the Discover as failed. The host records
	// it as a per-adapter error and continues the scan with other adapters
	// (matching the in-process soft-fail contract). Rows are ignored when
	// error is set.
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// warnings are non-fatal diagnostics surfaced to the host. Free-form.
	Warnings      []string `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_adapterplugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapterplugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_adapterplugin_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoverResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *DiscoverResponse) GetElements() []*contract.ContractElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *DiscoverResponse) GetTests() []*testcase.TestCase {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *DiscoverResponse) GetDocClaims() []*docclaim.DocClaim {
	if x != nil {
		return x.DocClaims
	}
	return nil
}

func (x *DiscoverResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DiscoverResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// PluginInfo is emitted in response to the `--sheaf-adapter-info` probe:
// the host spawns the executable with that single flag, reads one
// length-prefixed PluginInfo from stdout, and the child exits 0. Used for
// up-front protocol-version negotiation and `sheaf doctor` diagnostics
// without running a scan.
type PluginInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Roles           []Role                 `protobuf:"varint,4,rep,packed,name=roles,proto3,enum=sheaf.adapterplugin.v1.Role" json:"roles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_adapterplugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_adapterplugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_adapterplugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInfo) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_adapterplugin_proto protoreflect.FileDescriptor

const file_adapterplugin_proto_rawDesc = "" +
	"\n" +
	"\x13adapterplugin.proto\x12\x16sheaf.adapterplugin.v1\x1a\x0econtract.proto\x1a\x0ftest_case.proto\x1a\x0fdoc_claim.proto\"^\n" +
	"\x05Scope\x12\x18\n" +
	"\alibrary\x18\x01 \x03(\tR\alibrary\x12!\n" +
	"\falso_include\x18\x02 \x03(\tR\valsoInclude\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\"\xc9\x01\n" +
	"\rAdapterConfig\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\x12I\n" +
	"\x06option\x18\x03 \x03(\v21.sheaf.adapterplugin.v1.AdapterConfig.OptionEntryR\x06option\x1a9\n" +
	"\vOptionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\x0fDiscoverRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x120\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1c.sheaf.adapterplugin.v1.RoleR\x04role\x12\x1b\n" +
	"\trepo_path\x18\x03 \x01(\tR\brepoPath\x123\n" +
	"\x05scope\x18\x04 \x01(\v2\x1d.sheaf.adapterplugin.v1.ScopeR\x05scope\x12=\n" +
	"\x06config\x18\x05 \x01(\v2%.sheaf.adapterplugin.v1.AdapterConfigR\x06config\"\x9e\x02\n" +
	"\x10DiscoverResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12>\n" +
	"\belements\x18\x02 \x03(\v2\".sheaf.contract.v1.ContractElementR\belements\x121\n" +
	"\x05tests\x18\x03 \x03(\v2\x1b.sheaf.testcase.v1.TestCaseR\x05tests\x12:\n" +
	"\n" +
	"doc_claims\x18\x04 \x03(\v2\x1b.sheaf.docclaim.v1.DocClaimR\tdocClaims\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\"\x99\x01\n" +
	"\n" +
	"PluginInfo\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x122\n" +
	"\x05roles\x18\x04 \x03(\x0e2\x1c.sheaf.adapterplugin.v1.RoleR\x05roles*\x97\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ROLE_CONTRACT_ANCHOR\x10\x01\x12\x14\n" +
	"\x10ROLE_TEST_PARSER\x10\x02\x12\x13\n" +
	"\x0fROLE_DOC_PARSER\x10\x03\x12\x1b\n" +
	"\x17ROLE_RENDERED_REFERENCE\x10\x04\x12\x17\n" +
	"\x13ROLE_IMPLEMENTS_MAP\x10\x05B1Z/github.com/sheaf-data/sheaf/proto/adapterpluginb\x06proto3"

var (
	file_adapterplugin_proto_rawDescOnce sync.Once
	file_adapterplugin_proto_rawDescData []byte
)

func file_adapterplugin_proto_rawDescGZIP() []byte {
	file_adapterplugin_proto_rawDescOnce.Do(func() {
		file_adapterplugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapterplugin_proto_rawDesc), len(file_adapterplugin_proto_rawDesc)))
	})
	return file_adapterplugin_proto_rawDescData
}

var file_adapterplugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_adapterplugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_adapterplugin_proto_goTypes = []any{
	(Role)(0),                        // 0: sheaf.adapterplugin.v1.Role
	(*Scope)(nil),                    // 1: sheaf.adapterplugin.v1.Scope
	(*AdapterConfig)(nil),            // 2: sheaf.adapterplugin.v1.AdapterConfig
	(*DiscoverRequest)(nil),          // 3: sheaf.adapterplugin.v1.DiscoverRequest
	(*DiscoverResponse)(nil),         // 4: sheaf.adapterplugin.v1.DiscoverResponse
	(*PluginInfo)(nil),               // 5: sheaf.adapterplugin.v1.PluginInfo
	nil,                              // 6: sheaf.adapterplugin.v1.AdapterConfig.OptionEntry
	(*contract.ContractElement)(nil), // 7: sheaf.contract.v1.ContractElement
	(*testcase.TestCase)(nil),        // 8: sheaf.testcase.v1.TestCase
	(*docclaim.DocClaim)(nil),        // 9: sheaf.docclaim.v1.DocClaim
}
var file_adapterplugin_proto_depIdxs = []int32{
	6, // 0: sheaf.adapterplugin.v1.AdapterConfig.option:type_name -> sheaf.adapterplugin.v1.AdapterConfig.OptionEntry
	0, // 1: sheaf.adapterplugin.v1.DiscoverRequest.role:type_name -> sheaf.adapterplugin.v1.Role
	1, // 2: sheaf.adapterplugin.v1.DiscoverRequest.scope:type_name -> sheaf.adapterplugin.v1.Scope
	2, // 3: sheaf.adapterplugin.v1.DiscoverRequest.config:type_name -> sheaf.adapterplugin.v1.AdapterConfig
	7, // 4: sheaf.adapterplugin.v1.DiscoverResponse.elements:type_name -> sheaf.contract.v1.ContractElement
	8, // 5: sheaf.adapterplugin.v1.DiscoverResponse.tests:type_name -> sheaf.testcase.v1.TestCase
	9, // 6: sheaf.adapterplugin.v1.DiscoverResponse.doc_claims:type_name -> sheaf.docclaim.v1.DocClaim
	0, // 7: sheaf.adapterplugin.v1.PluginInfo.roles:type_name -> sheaf.adapterplugin.v1.Role
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_adapterplugin_proto_init() }
func file_adapterplugin_proto_init() {
	if File_adapterplugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapterplugin_proto_rawDesc), len(file_adapterplugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_adapterplugin_proto_goTypes,
		DependencyIndexes: file_adapterplugin_proto_depIdxs,
		EnumInfos:         file_adapterplugin_proto_enumTypes,
		MessageInfos:      file_adapterplugin_proto_msgTypes,
	}.Build()
	File_adapterplugin_proto = out.File
	file_adapterplugin_proto_goTypes = nil
	file_adapterplugin_proto_depIdxs = nil
}
