#!/usr/bin/env python3
"""Generate a COMPLETE, domain-grouped Fuchsia FIDL coverage config set +
manifest for the sheaf coverage-index fan-out.

Every library under <fuchsia>/sdk/fidl/ is assigned to exactly one domain
(a catch-all guarantees nothing is dropped), domains are clustered into
coarse index groups, and one contract-anchored config + manifest entry is
emitted per domain. Contract-complete (all FIDL protocols/methods/types).
Per-domain test/impl wiring is layered on from a hand-maintained overlay
(fuchsia-coverage-overlay.json) via the shared scripts/coverage_overlay.py
helper, re-applied on every run so regeneration is non-destructive. Each
ecosystem keeps its own overlay file (one per gen-<ecosystem>-coverage.py).

Reproducible + idempotent: re-run after a Fuchsia checkout update to
regenerate; an unchanged SDK + overlay yields byte-identical output.

  FUCHSIA_CHECKOUT  fuchsia tree (default /Volumes/T7/fuchsia)
  Usage:  python3 scripts/gen-fuchsia-coverage.py
  Then:   ./sheaf scan --manifest docs/examples/fuchsia-coverage-manifest.textproto \\
                       --output-dir docs/examples/fuchsia-coverage --repo $FUCHSIA_CHECKOUT
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import coverage_overlay  # noqa: E402  (sibling helper in scripts/)

FUCHSIA = os.environ.get("FUCHSIA_CHECKOUT", "/Volumes/T7/fuchsia")
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CFG_DIR = os.path.join(REPO, "docs/examples/fuchsia-coverage-configs")
MANIFEST = os.path.join(REPO, "docs/examples/fuchsia-coverage-manifest.textproto")
OVERLAY = os.path.join(REPO, "docs/examples/fuchsia-coverage-overlay.json")

# Concept-doc reports — the doc-centric clear/ambiguous/silent map of how each
# library group's narrative docs reference its FIDL contract — are generated by
# scripts/gen-fuchsia-concept-docs.py into the sibling
# fuchsia-coverage-concept-docs/ dir. They exist only for these library groups.
# Each coverage DOMAIN lights up its concept-doc reach-stats eyebrow link via a
# per-entry concept_docs_href, DERIVED from the domain's own library set (not a
# hand-maintained domain->report table): a domain covering exactly one of these
# links to that library's report (most specific); a domain covering more than
# one links to the combined all-fuchsia report, filtered (?library=) to just
# those libraries; a domain covering none gets no link.
CONCEPT_DOC_LIBS = {
    "fuchsia.driver.framework": "driver-framework.html",
    "fuchsia.io": "io.html",
    "fuchsia.ui.composition": "ui-composition.html",
    "fuchsia.ui.gfx": "ui-gfx.html",
}
# Sibling of fuchsia-coverage-contents/ (where each domain report renders), so a
# relative ../ href survives publishing alongside the coverage output.
CONCEPT_DOCS_REL = "../fuchsia-coverage-concept-docs"


def concept_docs_href(libs_csv):
    """Concept-doc report href for a domain's library CSV, or '' for no link.

    One covered library -> that library's report (most specific). More than one
    -> the combined all-fuchsia report filtered to exactly those libraries.
    """
    matched = [lib for lib in libs_csv.split(",") if lib in CONCEPT_DOC_LIBS]
    if len(matched) == 1:
        return f"{CONCEPT_DOCS_REL}/{CONCEPT_DOC_LIBS[matched[0]]}"
    if len(matched) > 1:
        return f"{CONCEPT_DOCS_REL}/all-fuchsia.html?library=" + ",".join(matched)
    return ""

# (domain label, coarse index group, [regex patterns]).  Ordered: the first
# domain whose any pattern matches a library name wins.  More-specific
# (hardware sub-splits) come first.  Patterns are anchored with re.match.
DOMAINS = [
    ("Hardware · Buses & I/O", "Hardware",
     [r"fuchsia\.hardware\.(usb|spi|i2c|gpio|pci|serial|sdmmc|sdio|sdhci|spmi|clock|platform|scsi|rpmb|skipblock|sharedmemory|hidbus|hid|registers|interconnect|dsp|sockettunnel)"]),
    ("Hardware · Display, GPU & Audio", "Hardware",
     [r"fuchsia\.hardware\.(display|gpu|audio|goldfish|virtio|sysmem|mediacodec|backlight|dsi|amlogiccanvas)"]),
    ("Hardware · Networking & Radio", "Hardware",
     [r"fuchsia\.hardware\.(network|ethernet|wlan|bluetooth|telephony|uwb|vsock|nfc)"]),
    ("Hardware · Power, Thermal & Sensors", "Hardware",
     [r"fuchsia\.hardware\.(power|powersource|vreg|thermal|temperature|trippoint|sensors?|battery|adc|pwm)"]),
    ("Hardware · Block & Storage", "Hardware",
     [r"fuchsia\.hardware\.(block|ufs|nand|ramdisk|storage)"]),
    ("Hardware · Security & RTC", "Hardware",
     [r"fuchsia\.hardware\.(tee|tpmimpl|tpm|securemem|rtc|hrtimer|fido)"]),
    ("Hardware · Other", "Hardware", [r"fuchsia\.hardware\."]),
    ("Drivers & Framework", "Hardware", [r"fuchsia\.driver", r"fdf"]),

    ("UI, Scenic & Composition", "Graphics & UI",
     [r"fuchsia\.ui", r"fuchsia\.scenic", r"fuchsia\.element", r"fuchsia\.sysmem"]),
    ("Accessibility & Input", "Graphics & UI",
     [r"fuchsia\.accessibility", r"fuchsia\.input"]),

    ("Networking", "Connectivity", [r"fuchsia\.net", r"fuchsia\.posix"]),
    ("Wireless (WLAN / LoWPAN)", "Connectivity",
     [r"fuchsia\.wlan", r"fuchsia\.lowpan", r"fuchsia\.location"]),
    ("Bluetooth", "Connectivity", [r"fuchsia\.bluetooth"]),
    ("Telephony & Weave", "Connectivity",
     [r"fuchsia\.telephony", r"fuchsia\.weave", r"fuchsia\.overnet"]),

    ("Media, Audio & Camera", "Media",
     [r"fuchsia\.media", r"fuchsia\.audio", r"fuchsia\.camera", r"fuchsia\.images?", r"fuchsia\.mediacodec", r"fuchsia\.drm"]),

    ("Storage & Packages", "System",
     [r"fuchsia\.io\b", r"fuchsia\.fs", r"fuchsia\.storage", r"fuchsia\.pkg", r"fuchsia\.paver",
      r"fuchsia\.fxfs", r"fuchsia\.blobfs", r"fuchsia\.update", r"fuchsia\.space", r"fuchsia\.io2?"]),
    ("Component & Runtime", "System",
     [r"fuchsia\.component", r"fuchsia\.sys", r"fuchsia\.process", r"fuchsia\.boot", r"fuchsia\.kernel",
      r"fuchsia\.elf", r"fuchsia\.data", r"fuchsia\.ldsvc", r"fuchsia\.dash", r"fuchsia\.scheduler",
      r"fuchsia\.ebpf", r"fuchsia\.device"]),
    ("Power & Memory", "System",
     [r"fuchsia\.power", r"fuchsia\.memory", r"fuchsia\.thermal", r"fuchsia\.cpu"]),
    ("Diagnostics & Tracing", "System",
     [r"fuchsia\.diagnostics", r"fuchsia\.tracing", r"fuchsia\.cobalt", r"fuchsia\.metrics",
      r"fuchsia\.inspect", r"fuchsia\.logger", r"fuchsia\.debugdata", r"fuchsia\.debugger",
      r"fuchsia\.feedback", r"fuchsia\.exception"]),
    ("Time", "System", [r"fuchsia\.time"]),
    ("Virtualization & Starnix", "System", [r"fuchsia\.virtualization", r"fuchsia\.starnix"]),
    ("Settings, Intl & Recovery", "System",
     [r"fuchsia\.settings", r"fuchsia\.recovery", r"fuchsia\.intl", r"fuchsia\.fonts",
      r"fuchsia\.buildinfo", r"fuchsia\.factory", r"fuchsia\.hwinfo", r"fuchsia\.systeminfo",
      r"fuchsia\.acpi"]),

    ("Identity & Security", "Security & Identity",
     [r"fuchsia\.identity", r"fuchsia\.auth", r"fuchsia\.tee", r"fuchsia\.tpm", r"fuchsia\.kms",
      r"fuchsia\.attestation", r"fuchsia\.fido", r"fuchsia\.security"]),

    ("Developer & Testing", "Developer",
     [r"fuchsia\.developer", r"fuchsia\.test", r"fuchsia\.testing", r"fuchsia\.fdomain"]),

    ("Cast", "Product & UX", [r"fuchsia\.cast"]),
    ("Session & Apps", "Product & UX", [r"fuchsia\.session", r"fuchsia\.app"]),
]
OTHER = ("Other (uncategorized)", "Other")


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main():
    fidl_root = os.path.join(FUCHSIA, "sdk/fidl")
    if not os.path.isdir(fidl_root):
        sys.exit(f"gen-fuchsia-coverage: {fidl_root} not found (set FUCHSIA_CHECKOUT)")
    libs = sorted(d for d in os.listdir(fidl_root) if os.path.isdir(os.path.join(fidl_root, d)))

    # Hand-maintained test/impl overlay, re-applied on every run so the
    # generator is non-destructive (impl/test source paths don't follow from
    # FIDL library names — they're human-curated). See scripts/coverage_overlay.py.
    overlay = coverage_overlay.load_overlay(OVERLAY)

    assign = {}  # label -> [group, [libs]]
    for lib in libs:
        placed = False
        for label, group, pats in DOMAINS:
            if any(re.match(p, lib) for p in pats):
                assign.setdefault(label, [group, []])[1].append(lib)
                placed = True
                break
        if not placed:
            assign.setdefault(OTHER[0], [OTHER[1], []])[1].append(lib)

    os.makedirs(CFG_DIR, exist_ok=True)
    entries = []
    for label, (group, liblist) in assign.items():
        sl = slugify(label)
        cfg = os.path.join(CFG_DIR, sl + ".textproto")
        with open(cfg, "w") as f:
            f.write("version: 1\n")
            # idl_prefix lets the markdown matcher attribute "fuchsia.*" prose
            # mentions to FIDL elements (the docs.concepts surface + doc-lag).
            f.write(f'project {{ name: "fuchsia" display_name: "Fuchsia OS — {label}" idl_prefix: "fuchsia" }}\n')
            f.write("scope {}\n")
            f.write('contract_anchor {\n  name: "fidl"\n  fidl {\n')
            for lib in liblist:
                f.write(f'    include: "sdk/fidl/{lib}/**/*.fidl"\n')
            f.write('    exclude: "sdk/fidl/**/test/**"\n  }\n}\n')
            # Concept-docs source: a uniform markdown doc_parser over the Fuchsia
            # doc trees. Feeds docs.concepts (cross-file prose), which carries
            # the doc-lag signal — reference docs are inline in the .fidl, so
            # they are never lagged; the conceptual narrative is what drifts.
            f.write('doc_parser {\n  name: "markdown"\n  markdown {\n')
            f.write('    include: "docs/development/**/*.md"\n')
            f.write('    include: "docs/concepts/**/*.md"\n')
            f.write('    include: "docs/reference/fidl/**/*.md"\n')
            f.write('  }\n}\n')
            # Hand-curated test/impl wiring (if any). implements_map stays as
            # collected IMPLEMENTS evidence, but "implementations" is left out of
            # surfaces_required, so it is not a headline chip.
            ov = coverage_overlay.entry_for(overlay, sl)
            coverage_overlay.render_overlay_blocks(f, ov)
            f.write('analyzer { name: "thin-reference"      severity: WARNING }\n')
            f.write('analyzer { name: "documented-untested" severity: WARNING }\n')
            f.write('analyzer { name: "tested-undocumented" severity: INFO }\n')
            # Only the Reference-docs chip is shown. docs.concepts is required so
            # the docs tile renders (its gate) and carries the lag; tests /
            # examples / implementations are intentionally NOT headline chips.
            f.write('surfaces_required: "docs.reference"\n')
            f.write('surfaces_required: "docs.concepts"\n')
        entries.append((cfg, ",".join(liblist), label, group, sl + ".html"))

    coverage_overlay.warn_stale(overlay, {slugify(l) for l in assign})

    with open(MANIFEST, "w") as f:
        f.write("# MonorepoManifest — generated by scripts/gen-fuchsia-coverage.py\n")
        f.write(f"# {len(libs)} sdk/fidl libraries across {len(assign)} domains; nothing dropped.\n")
        manifest_dir = os.path.dirname(MANIFEST)
        for cfg, liblist, label, group, out in entries:
            # config_path RELATIVE to the manifest's directory so the manifest
            # is portable across checkouts (the fan-out resolves entry
            # config_path against the manifest dir).
            rel_cfg = os.path.relpath(cfg, manifest_dir)
            f.write("entries {\n")
            f.write(f'  config_path: "{rel_cfg}"\n')
            f.write(f'  library: "{liblist}"\n')
            f.write('  ecosystem: "fidl"\n')
            f.write(f'  library_label: "{label}"\n')
            # group = the domain itself, so the coverage index groups reports
            # BY DOMAIN (one clickable card each). The coarse group stays only
            # for the generation summary below.
            f.write(f'  group: "{label}"\n')
            f.write(f'  output: "{out}"\n')
            # Per-entry link to the sibling concept-doc report covering this
            # domain's libraries (omitted when none of the domain's libraries
            # has a concept-doc report). Lights up the coverage report's
            # concept-doc reach-stats eyebrow via NavContext.ConceptDocsHref.
            href = concept_docs_href(liblist)
            if href:
                f.write(f'  concept_docs_href: "{href}"\n')
            f.write("}\n")

    total = 0
    for label, (group, liblist) in sorted(assign.items(), key=lambda x: (x[1][0], x[0])):
        print(f"{group:18} | {label:34} | {len(liblist):3}")
        total += len(liblist)
    print(f"\nTOTAL {total} libs / {len(assign)} domains  (expected {len(libs)}; "
          f"{'OK no drops' if total == len(libs) else 'MISMATCH!'})")
    other = assign.get(OTHER[0], [None, []])[1]
    if other:
        print(f"\nOther bucket ({len(other)}): {', '.join(other)}")


if __name__ == "__main__":
    main()
