#!/usr/bin/env bash
# Build a staging tree + emit a MonorepoManifest textproto for the
# Fuchsia FIDL families that ship a coverage config in this repo.
#
# Why a staging tree? The fan-out runner (`sheaf scan --manifest`) stages
# an entry's categorization rules only when they sit next to the config as
# a sibling named exactly `categorization-rules.textproto`. The shipped
# Fuchsia rules are named `fuchsia-<family>-coverage-rules.textproto`, so
# this script copies each family's config + rules into a per-family
# subdirectory of $STAGE_DIR, renaming the rules to the sibling name the
# runner looks for. The configs themselves are unchanged.
#
# Families (one manifest entry each, grouped into index "domains"):
#   fuchsia.io                       -> Storage & IO
#   fuchsia.ui.composition           -> UI & Graphics
#   fuchsia.ui.gfx                   -> UI & Graphics
#   fuchsia.driver.framework         -> Driver Framework   (single library)
#   driver-framework-family (10 libs)-> Driver Framework   (DFv2 + adjacent)
#
# The driver-framework-family entry rolls 10 fuchsia.driver.* libraries
# into one report via a comma-separated `library` list (the same list
# scripts/regen-example-reports.sh passes via --library). Its config has an
# empty scope{}; the manifest's `library` field supplies the narrowing,
# exactly as the --library flag does for the standalone report.
#
# This script ONLY builds the staging tree and emits the manifest on
# stdout. It does NOT run the fan-out — that is the caller's invocation:
#
#   scripts/generate-fuchsia-manifest.sh > /tmp/fuchsia-manifest.textproto
#   sheaf scan --manifest /tmp/fuchsia-manifest.textproto \
#              --output-dir /tmp/fuchsia-coverage-index \
#              --repo "$FUCHSIA_CHECKOUT"
#   open /tmp/fuchsia-coverage-index/index.html
#
# Env:
#   FUCHSIA_STAGE_DIR  staging tree root         (default /tmp/fuchsia-stage)
#   FUCHSIA_ECOSYSTEM  render ecosystem per entry (default fidl)
#
# Generic by design: any FIDL/proto monorepo plugs into the same
# `sheaf scan --manifest` runner; this one ships because Fuchsia is the
# current driver (mirrors scripts/generate-pigweed-manifest.sh).

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS="$REPO_ROOT/docs/examples"
STAGE_DIR="${FUCHSIA_STAGE_DIR:-/tmp/fuchsia-stage}"
FUCHSIA_ECOSYSTEM="${FUCHSIA_ECOSYSTEM:-fidl}"

# stage_family <slug> <config-basename> <rules-basename>
# Copies the config + rules into $STAGE_DIR/<slug>/, renaming rules to the
# sibling name the fan-out runner stages. Prints the staged config path.
stage_family() {
  local slug="$1" config_base="$2" rules_base="$3"
  local src_config="$DOCS/$config_base"
  local src_rules="$DOCS/$rules_base"
  if [[ ! -f "$src_config" ]]; then
    echo "generate-fuchsia-manifest: missing config $src_config" >&2
    return 1
  fi
  local dir="$STAGE_DIR/$slug"
  mkdir -p "$dir"
  cp "$src_config" "$dir/config.textproto"
  if [[ -f "$src_rules" ]]; then
    cp "$src_rules" "$dir/categorization-rules.textproto"
  fi
  printf '%s/config.textproto' "$dir"
}

# emit_entry <config-path> <library> <library-label> <group> <output>
emit_entry() {
  printf 'entries {\n'
  printf '  config_path: "%s"\n' "$1"
  printf '  library: "%s"\n' "$2"
  printf '  ecosystem: "%s"\n' "$FUCHSIA_ECOSYSTEM"
  printf '  library_label: "%s"\n' "$3"
  printf '  group: "%s"\n' "$4"
  printf '  output: "%s"\n' "$5"
  printf '}\n'
}

DFF_FAMILY_LIBS="fuchsia.driver.framework,fuchsia.driver.development,fuchsia.driver.host,fuchsia.driver.test,fuchsia.driver.compat,fuchsia.driver.index,fuchsia.driver.loader,fuchsia.driver.registrar,fuchsia.driver.token,fuchsia.driver.test.logger"

rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"

echo "# MonorepoManifest — generated by scripts/generate-fuchsia-manifest.sh"
echo "# staging tree: $STAGE_DIR"
echo "# ecosystem: $FUCHSIA_ECOSYSTEM"

emitted=0

# fuchsia.io  (also_include fuchsia.unknown via the config)
cfg="$(stage_family io fuchsia-io-coverage-config.textproto fuchsia-io-coverage-rules.textproto)" \
  && emit_entry "$cfg" "fuchsia.io" "fuchsia.io" "Storage & IO" "fuchsia.io.html" \
  && emitted=$((emitted + 1))

# fuchsia.ui.composition
cfg="$(stage_family ui-composition fuchsia-ui-composition-coverage-config.textproto fuchsia-ui-composition-coverage-rules.textproto)" \
  && emit_entry "$cfg" "fuchsia.ui.composition" "fuchsia.ui.composition" "UI & Graphics" "fuchsia.ui.composition.html" \
  && emitted=$((emitted + 1))

# fuchsia.ui.gfx (deprecated predecessor)
cfg="$(stage_family ui-gfx fuchsia-ui-gfx-coverage-config.textproto fuchsia-ui-gfx-coverage-rules.textproto)" \
  && emit_entry "$cfg" "fuchsia.ui.gfx" "fuchsia.ui.gfx (deprecated)" "UI & Graphics" "fuchsia.ui.gfx.html" \
  && emitted=$((emitted + 1))

# fuchsia.driver.framework (single library)
cfg="$(stage_family driver-framework fuchsia-driver-framework-coverage-config.textproto fuchsia-driver-framework-coverage-rules.textproto)" \
  && emit_entry "$cfg" "fuchsia.driver.framework" "fuchsia.driver.framework" "Driver Framework" "fuchsia.driver.framework.html" \
  && emitted=$((emitted + 1))

# Driver Framework family (10 fuchsia.driver.* libraries; shares the
# single-library rules file — the C++ test corpus is the same trees).
cfg="$(stage_family driver-framework-family fuchsia-driver-framework-family-coverage-config.textproto fuchsia-driver-framework-coverage-rules.textproto)" \
  && emit_entry "$cfg" "$DFF_FAMILY_LIBS" "Driver Framework family (DFv2 + adjacent)" "Driver Framework" "fuchsia-driver-framework-family.html" \
  && emitted=$((emitted + 1))

echo "# $emitted entr(ies) staged" >&2
