#!/usr/bin/env bash
# Emit a MonorepoManifest textproto for the Pigweed C++ API modules.
#
# Reads PIGWEED_MODULES from $PIGWEED_CHECKOUT (default
# /Volumes/T7/pigweed) and emits one manifest entry per module that has
# a corresponding docs/examples/pigweed-<mod>-coverage-config.textproto
# in this sheaf repo. The library label for each entry is pulled from
# the config's scope.library; the render ecosystem defaults to "cpp"
# (override with PIGWEED_ECOSYSTEM) since the shipped Pigweed configs
# scan the C++ public-header contract surface.
#
# config_path values are REPO-RELATIVE (relative to this sheaf repo).
# When the manifest is written outside the repo (e.g. /tmp), anchor them
# with `sheaf scan --config-root <repo>`.
#
# This script ONLY emits the manifest on stdout. It does not run the
# fan-out — that is the user's `sheaf scan --manifest` invocation:
#
#   scripts/generate-pigweed-manifest.sh > /tmp/pigweed-manifest.textproto
#   sheaf scan --manifest /tmp/pigweed-manifest.textproto \
#              --config-root "$(pwd)" \
#              --output-dir /tmp/pigweed-fanout \
#              --repo "$PIGWEED_CHECKOUT"
#
# Generic by design: Cargo / Bazel / Lerna monorepos plug into the same
# `sheaf scan --manifest` runner by supplying their own list-generator;
# this one ships because Pigweed is the current driver.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PIGWEED_CHECKOUT="${PIGWEED_CHECKOUT:-/Volumes/T7/pigweed}"
PIGWEED_ECOSYSTEM="${PIGWEED_ECOSYSTEM:-cpp}"

MODULES_FILE="$PIGWEED_CHECKOUT/PIGWEED_MODULES"
if [[ ! -f "$MODULES_FILE" ]]; then
  echo "generate-pigweed-manifest: $MODULES_FILE not found" >&2
  echo "set PIGWEED_CHECKOUT to your Pigweed checkout (current: $PIGWEED_CHECKOUT)" >&2
  exit 1
fi

emitted=0
echo "# MonorepoManifest — generated by scripts/generate-pigweed-manifest.sh"
echo "# source: $MODULES_FILE"
while IFS= read -r module || [[ -n "$module" ]]; do
  module="${module%%#*}"               # strip trailing comments
  module="$(echo "$module" | tr -d '[:space:]')"
  [[ -z "$module" ]] && continue

  config="docs/examples/pigweed-${module}-coverage-config.textproto"
  [[ -f "$REPO_ROOT/$config" ]] || continue

  # Emit an ABSOLUTE config_path. The fan-out runner resolves
  # config_path relative to the manifest file's directory, so a
  # repo-relative path only works when the manifest is saved at the
  # repo root. Absolute keeps the manifest portable (it's commonly
  # written to /tmp).
  config_abs="$REPO_ROOT/$config"

  # Pull the scanned library from the config's scope.library; fall back
  # to the module name if the field can't be read.
  library="$(grep -oE 'library:[[:space:]]*"[^"]+"' "$config_abs" | head -1 | sed -E 's/.*"([^"]+)".*/\1/')"
  [[ -z "$library" ]] && library="$module"

  printf 'entries {\n'
  printf '  config_path: "%s"\n' "$config_abs"
  printf '  library: "%s"\n' "$library"
  printf '  ecosystem: "%s"\n' "$PIGWEED_ECOSYSTEM"
  printf '  library_label: "%s"\n' "$module"
  printf '  output: "pigweed-%s.html"\n' "$module"
  printf '}\n'
  emitted=$((emitted + 1))
done < "$MODULES_FILE"

echo "# $emitted module(s) had a matching coverage config" >&2
