// Source-map schema. On disk this file is conventionally named
// `categorization-rules.textproto` at the project repo root. The
// user-facing concept is the project's "source map" — a declaration
// of which paths in the source tree produce which kind of evidence
// (docs.reference, docs.concepts, tests.integration_tests,
// examples, ...).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: categorization.proto

package categorization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Category      []*Category            `protobuf:"bytes,2,rep,name=category,proto3" json:"category,omitempty"`
	Ownership     []*Ownership           `protobuf:"bytes,3,rep,name=ownership,proto3" json:"ownership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rules) Reset() {
	*x = Rules{}
	mi := &file_categorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rules) ProtoMessage() {}

func (x *Rules) ProtoReflect() protoreflect.Message {
	mi := &file_categorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rules.ProtoReflect.Descriptor instead.
func (*Rules) Descriptor() ([]byte, []int) {
	return file_categorization_proto_rawDescGZIP(), []int{0}
}

func (x *Rules) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Rules) GetCategory() []*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Rules) GetOwnership() []*Ownership {
	if x != nil {
		return x.Ownership
	}
	return nil
}

type Category struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dotted path matching the CoverageProfile field hierarchy.
	// Examples: "tests.unit_tests", "docs.guide.migrations".
	DottedPath   string   `protobuf:"bytes,1,opt,name=dotted_path,json=dottedPath,proto3" json:"dotted_path,omitempty"`
	Paths        []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	ExcludePaths []string `protobuf:"bytes,3,rep,name=exclude_paths,json=excludePaths,proto3" json:"exclude_paths,omitempty"`
	// section_excludes / section_includes filter doc claims by the
	// heading stack the claim sits under (see DocClaim.section_path).
	// Matching is case-insensitive substring against any heading in
	// the stack.
	//
	//   - section_excludes: if any pattern matches any heading, the
	//     category does NOT apply to this claim (even if its path matches).
	//   - section_includes: if non-empty, the category applies only when
	//     at least one pattern matches at least one heading. If empty,
	//     no include filter is applied.
	//
	// Filters are skipped entirely when the claim's section_path is
	// empty (preamble text or a non-markdown source). Together these
	// let a docs.concepts rule route README.md to concepts while
	// excluding reference-shaped sections like `## Options`.
	SectionExcludes []string `protobuf:"bytes,4,rep,name=section_excludes,json=sectionExcludes,proto3" json:"section_excludes,omitempty"`
	SectionIncludes []string `protobuf:"bytes,5,rep,name=section_includes,json=sectionIncludes,proto3" json:"section_includes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_categorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_categorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_categorization_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetDottedPath() string {
	if x != nil {
		return x.DottedPath
	}
	return ""
}

func (x *Category) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Category) GetExcludePaths() []string {
	if x != nil {
		return x.ExcludePaths
	}
	return nil
}

func (x *Category) GetSectionExcludes() []string {
	if x != nil {
		return x.SectionExcludes
	}
	return nil
}

func (x *Category) GetSectionIncludes() []string {
	if x != nil {
		return x.SectionIncludes
	}
	return nil
}

type Ownership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"` // optional; exact-match library name
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Subscribe     bool                   `protobuf:"varint,4,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ownership) Reset() {
	*x = Ownership{}
	mi := &file_categorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ownership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ownership) ProtoMessage() {}

func (x *Ownership) ProtoReflect() protoreflect.Message {
	mi := &file_categorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ownership.ProtoReflect.Descriptor instead.
func (*Ownership) Descriptor() ([]byte, []int) {
	return file_categorization_proto_rawDescGZIP(), []int{2}
}

func (x *Ownership) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Ownership) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Ownership) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Ownership) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

var File_categorization_proto protoreflect.FileDescriptor

const file_categorization_proto_rawDesc = "" +
	"\n" +
	"\x14categorization.proto\x12\x17sheaf.categorization.v1\"\xa2\x01\n" +
	"\x05Rules\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12=\n" +
	"\bcategory\x18\x02 \x03(\v2!.sheaf.categorization.v1.CategoryR\bcategory\x12@\n" +
	"\townership\x18\x03 \x03(\v2\".sheaf.categorization.v1.OwnershipR\townership\"\xbc\x01\n" +
	"\bCategory\x12\x1f\n" +
	"\vdotted_path\x18\x01 \x01(\tR\n" +
	"dottedPath\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12#\n" +
	"\rexclude_paths\x18\x03 \x03(\tR\fexcludePaths\x12)\n" +
	"\x10section_excludes\x18\x04 \x03(\tR\x0fsectionExcludes\x12)\n" +
	"\x10section_includes\x18\x05 \x03(\tR\x0fsectionIncludes\"q\n" +
	"\tOwnership\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1c\n" +
	"\tsubscribe\x18\x04 \x01(\bR\tsubscribeB2Z0github.com/sheaf-data/sheaf/proto/categorizationb\x06proto3"

var (
	file_categorization_proto_rawDescOnce sync.Once
	file_categorization_proto_rawDescData []byte
)

func file_categorization_proto_rawDescGZIP() []byte {
	file_categorization_proto_rawDescOnce.Do(func() {
		file_categorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_categorization_proto_rawDesc), len(file_categorization_proto_rawDesc)))
	})
	return file_categorization_proto_rawDescData
}

var file_categorization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_categorization_proto_goTypes = []any{
	(*Rules)(nil),     // 0: sheaf.categorization.v1.Rules
	(*Category)(nil),  // 1: sheaf.categorization.v1.Category
	(*Ownership)(nil), // 2: sheaf.categorization.v1.Ownership
}
var file_categorization_proto_depIdxs = []int32{
	1, // 0: sheaf.categorization.v1.Rules.category:type_name -> sheaf.categorization.v1.Category
	2, // 1: sheaf.categorization.v1.Rules.ownership:type_name -> sheaf.categorization.v1.Ownership
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_categorization_proto_init() }
func file_categorization_proto_init() {
	if File_categorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_categorization_proto_rawDesc), len(file_categorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_categorization_proto_goTypes,
		DependencyIndexes: file_categorization_proto_depIdxs,
		MessageInfos:      file_categorization_proto_msgTypes,
	}.Build()
	File_categorization_proto = out.File
	file_categorization_proto_goTypes = nil
	file_categorization_proto_depIdxs = nil
}
